
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$currentCat = $objectManager->get('\Magento\Framework\Registry');
/** @var \Magento\Catalog\Model\Category $currentCategory */
$currentCategory = $currentCat->registry('current_category');
?>

<?php if( $currentCategory ): ?>
    <div class="heading_product_list mb mobile-listing-title">
        <h2 class="">
            <strong class="count-products-category-view-mobile"></strong>
            <span class="count-products-category-view-mobile-text"></span>
        </h2>
    </div>
<?php endif; ?>

