
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$currentCat = $objectManager->get('\Magento\Framework\Registry');
/** @var \Magento\Catalog\Model\Category $currentCategory */
$currentCategory = $currentCat->registry('current_category');
?>

<?php if( $currentCategory ): ?>
    <div class="heading_product_list">
        <h2 class="hide-mobile">
            <span class="count-products-category-view-desktop"></span><?= $currentCategory->getName(); ?>
        </h2>
    </div>
<?php endif; ?>