<div class="faqs-block" id="faqs-block">
    <div class="block block-collapsible-nav collapsible-custom">
        <div class="content block-collapsible-nav-content" id="block-collapsible-nav">
            <ul class="nav items">
                <li class="nav item current"><a href="#tab-0">{{trans "General"}}</a></li>
                <li class="nav item"><a href="#tab-1">{{trans "Argentina"}}</a></li>
                <li class="nav item"><a href="#tab-2">{{trans "Brazil"}}</a></li>
                <li class="nav item"><a href="#tab-3">{{trans "Bolivia"}}</a></li>
                <li class="nav item"><a href="#tab-4">{{trans "Chile"}}</a></li>
                <li class="nav item"><a href="#tab-5">{{trans "Colombia"}}</a></li>
                <li class="nav item"><a href="#tab-6">{{trans "Paraguay"}}</a></li>
                <li class="nav item"><a href="#tab-7">{{trans "Peru"}}</a></li>
                <li class="nav item"><a href="#tab-8">{{trans "Uruguay"}}</a></li>
            </ul>
        </div>
    </div>
    <div class="faq-tabs pull-right">
        {{block class="Magento\Cms\Block\Block" block_id="faq_general"}}
        {{block class="Magento\Cms\Block\Block" block_id="faq_argentina"}}
        {{block class="Magento\Cms\Block\Block" block_id="faq_brazil"}}
        {{block class="Magento\Cms\Block\Block" block_id="faq_bolivia"}}
        {{block class="Magento\Cms\Block\Block" block_id="faq_chile"}}
        {{block class="Magento\Cms\Block\Block" block_id="faq_colombia"}}
        {{block class="Magento\Cms\Block\Block" block_id="faq_paraguay"}}
        {{block class="Magento\Cms\Block\Block" block_id="faq_peru"}}
        {{block class="Magento\Cms\Block\Block" block_id="faq_uruguay"}}
    </div>
</div>