<style>
    .status_green, .status_yellow, .status_gray, .status_black{
        border-radius: 15px;
        color: #ffffff;
        display: block;
        font-weight: bold;
        padding: 2px 5px;
        text-align: center;
        width: 100px;
    }
    .status_gray {
        background-color: #999999;
    }
    .status_green {
        background-color: #468847;
    }
    .status_yellow{
        background-color: #f89406;
    }
    .status_black{
        background-color: black;
    }
</style>
<?php echo $block->getGridHtml(); ?>