<?php $booking = $block->getBkBookingItem(); ?>
<?php $request = $this->getBookingRequest(); // only type intervals ?>
<?php $maxBooking = $this->getBkHelperDate()->getFieldSetting('bookingsystem/setting/max_booking') ?>
<?php $addonsSelles = $block->getAddonsSelles(); ?>
<?php $bkIntCurrentTime = $block->getBkTmpTime(); ?>
<input type="hidden" name="exist_wishlist" id="exist_wishlist" value="<?php echo (isset($request['exist_wishlist'])) ? '1' : '0' ?>"/>
<input type="hidden" name="extra_options_regular_services" id="extra-options-rs" value="" />
<input type="hidden" name="exist_wishlist_intervarl_one" id="exist-wishlist-intervarl-one" value="<?= (isset($request['interval_one'])) ? $request['interval_one'] : '' ?>"/>
<input type="hidden" name="exist_wishlist_intervarl_two" id="exist-wishlist-intervarl-two" value="<?= (isset($request['interval_two'])) ? $request['interval_two'] : '' ?>"/>
<input type="hidden" name="bk_item_id" value="<?php echo $request['item_id']; ?>"  />
<input type="hidden" id="is-round-trip" name="isRoundTrip" value="1">
<div class="simple-booking-form booking-form">

	<div class="row">
		<div class="col-sm-6 col-xs-6">
			<div class="checkbox">
                <input
                        value="1"
                        id="option-going"
                        name="option_going_roundtrip"
                        type="radio"
                        class="cls-to-add-to-wishlist"
                        data-selector="optionsbooking[goingroundtrip]"
                    <?php echo (isset($request['goingroundtrip']) && $request['goingroundtrip'] == '1')
                        ? ' checked'
                        : (!isset($request['goingroundtrip']))
                            ? ' checked' : '' ; ?>
                />
                <label class="label-radio" for="option-going"></label>
                <label class="label-radio-text" for="option-going">
					 <?= __('Going') ?>
				</label>
			</div>
		</div>
		<div class="col-sm-6 col-xs-6">
			<div class="checkbox">
                <input
                        value="2"
                        id="option-roundtrip"
                        name="option_going_roundtrip"
                        type="radio"
                        class="cls-to-add-to-wishlist"
                        data-selector="optionsbooking[goingroundtrip]"

                    <?php echo (isset($request['goingroundtrip']) && $request['goingroundtrip'] == '2')
                        ? ' checked'
                        : '' ; ?>
                />
                <label class="label-radio" for="option-roundtrip"></label>
                <label class="label-radio-text" for="option-roundtrip">
                    <?= __('Roundtrip') ?>
                </label>
			</div>
		</div>
	</div>
    <div class="simple-booking-form-input">
		<?php $firstPrice = $block->getBkCurrentPrice(); ?>
		<div class="booking-per-day"><span><?php echo $block->getBkPriceHelper()->currency($firstPrice,true,false); ?></span> <?php echo __('Per Session'); ?></div>
		<div class="date-box date-box-checkin mt-sm">
			<div class="input-date">
				<label><?php echo __('Date of arrival:'); ?></label>
				<div class="form-group" >
					<div class="select-date" >
					<i id="check-in-button" class="fa fa-calendar input-icon"></i>
                        <span class="tooltip-box">
                            <span class="label-tooltip available-tooltip"></span>
                            <span class="tooltip available-tooltip-content"><?php echo __('Last Minute Booking Available'); ?></span>
                        </span>
                        <input
                                type="text"
                                id="bk-checkin-checkout"
                                name="bk_checkin_checkout"
                                value="<?php echo ($request['check_in'] != '') ? $request['check_in'] : ''; ?>"
                                class="form-control" onfocus="blur();"
                                placeholder="<?php echo __('Select Date') ?>" />
                        <input
							type="hidden"
							class="form-control input-text cls-to-add-to-wishlist"
							name="check_in"
							id="check-in"
							value="<?php echo $request['check_in']; ?>"
							data-selector="optionsbooking[check_in]" />
					<input class="form-control input-text" type="hidden" name="bk_temp_check_in" id="bk-temp-check-in" value="<?php echo $request['check_in']; ?>" onfocus="blur();" />
					</div>
				</div>
			</div>
			<div id="time-intervals-hours" class="select-time-intervals">

			</div>
		</div>
        <div class="clear"></div>
		<div class="date-box date-box-checkin-two mt-sm">
			<div class="input-date">
				<label><?php echo __('Date of departure:'); ?></label>
				<div class="form-group" >
					<div class="select-date" >
						<i id="check-in-button" class="fa fa-calendar input-icon"></i>
						<input type="text"  id="bk-checkin-checkout-two" name="bk_checkin_checkout_two"
							   value="<?php echo ($request['check_in_two'] != '') ? $request['check_in_two'] : ''; ?>" class="form-control" onfocus="blur();"
                        placeholder="<?php echo __('Select Date') ?>" />
						<input
							type="hidden"
							class="form-control input-text cls-to-add-to-wishlist"
							name="check_in_two"
							id="check-in-two"
							value="<?php echo $request['check_in_two']; ?>"
							data-selector="optionsbooking[check_in_two]"
						/>
						<input class="form-control input-text" type="hidden" name="bk_temp_check_in_two" id="bk-temp-check-in-two" value="<?php echo $request['check_in_two']; ?>" onfocus="blur();">
					</div>
				</div>
			</div>
			<div id="time-intervals-hours-two" class="select-time-intervals">

			</div>
		</div>
		<?php if(count($addonsSelles)) : ?>
			<div class="addons-cross-sells">
				<dl>
					<?php foreach($addonsSelles as $addonsSelle) : ?>
						<?php $requestAddon =  isset($request['addons'][$addonsSelle->getId()]) ? $request['addons'][$addonsSelle->getId()] : ''; ?>
						<?php $addonRadioCheckoxClass = ''; ?>
						<?php if($addonsSelle->getOptionType() == 4 || $addonsSelle->getOptionType() == 5) :  ?>
							<?php $addonRadioCheckoxClass = 'bk-addon-radio-checkbox';  ?>
							<?php if($addonsSelle->getOptionRequired() == 1) { $addonRadioCheckoxClass .= ' required-empty'; } ?>
						<?php endif; ?>
						<dt>
							<label for="addon-<?php echo $addonsSelle->getId(); ?>" <?php if ($addonsSelle->getOptionRequired() == 1) { echo 'class="required"'; } ?> >
								<?php if ( $addonsSelle->getOptionRequired() == 1) { echo '<em>*</em>'; } ?>
								<?php $title = $block->getBkHelperText()->showTranslateText($addonsSelle->getOptionTitle(),$addonsSelle->getOptionTitleTranslate()); ?>
								<?php echo $title; ?>
								<?php
								if ( $addonsSelle->getOptionPrice() > 0 ) {
									echo  '<span class="price-notice"> +<span class="price">'.$block->getBkPriceHelper()->currency($addonsSelle->getOptionPrice(), true, false).'</span></span>';
								}
								?>
							</label>
						</dt>
						<dd <?php if($addonRadioCheckoxClass != '') { ?>class="<?php echo $addonRadioCheckoxClass; ?>" id="bk-addon-radio-checkbox-<?php echo $addonsSelle->getId(); ?>"<?php } ?>>
							<div class="addons-sells-item input-box">
								<?php if($addonsSelle->getOptionType() == 2) : ?>
									<select
										class="select-addons-item<?php if($addonsSelle->getOptionRequired() == 1) echo ' required-empty'; ?> cls-to-add-to-wishlist"
										name="addons[<?php echo $addonsSelle['option_id'] ?>]"
										id="addons_<?php echo $addonsSelle['option_id'] ?>"
										data-selector="optionsbooking[<?php echo $addonsSelle['option_id'] ?>]"
									>
										<option value=""><?php echo __('Select Options'); ?></option>
										<?php $selectValues = $block->getBkOptionSelectValues($addonsSelle->getId()); ?>
										<?php if(count($selectValues)) : ?>
											<?php foreach($selectValues as $selectValue) : ?>
												<option value="<?php echo $selectValue->getId(); ?>" <?php if($requestAddon == $selectValue->getId()) { echo 'selected="selected"'; } ?>>
													<?php $valueTitle = $block->getBkHelperText()->showTranslateText($selectValue->getDropdownTitle(),$selectValue->getDropdownTitleTranslate()); ?>
													<?php echo $valueTitle; ?>
													<?php
													if ( $selectValue->getDropdownPrice() > 0 ) { echo ' +'.$block->getBkPriceHelper()->currency( $selectValue->getDropdownPrice(), true, false); }
													?>
												</option>
											<?php endforeach; ?>
										<?php endif; ?>
									</select>
								<?php elseif($addonsSelle->getOptionType() == 3) : ?>
									<select
										multiple
										class="select-addons-item<?php if($addonsSelle->getOptionRequired() == 1) echo ' required-empty'; ?> cls-to-add-to-wishlist"
										name="addons[<?php echo $addonsSelle['option_id'] ?>][]"
										id="addons_<?php echo $addonsSelle['option_id'] ?>"
										data-selector="optionsbooking[<?php echo $addonsSelle['option_id'] ?>]"
									>
										<?php $selectValues = $block->getBkOptionSelectValues($addonsSelle->getId()); ?>
										<?php if(count($selectValues)) : ?>
											<?php foreach($selectValues as $selectValue) : ?>
												<option value="<?php echo $selectValue->getId(); ?>" <?php if(is_array($requestAddon) && count($requestAddon) && in_array($selectValue->getId(),$requestAddon)) { echo 'selected="selected"'; } ?>>
													<?php $valueTitle = $block->getBkHelperText()->showTranslateText($selectValue->getDropdownTitle(),$selectValue->getDropdownTitleTranslate()); ?>
													<?php echo $valueTitle; ?>
													<?php
													if ( $selectValue->getDropdownPrice() > 0 ) { echo ' +'.$block->getBkPriceHelper()->currency( $selectValue->getDropdownPrice(), true, false); }
													?>
												</option>
											<?php endforeach; ?>
										<?php endif; ?>
									</select>
								<?php elseif($addonsSelle->getOptionType() == 4) : ?>
									<?php $readioValues = $block->getBkOptionSelectValues($addonsSelle->getId()); ?>
									<?php if(count($readioValues)) : ?>
										<?php foreach($readioValues as $key => $readioValue) : ?>
											<div class="addons-input-item">
												<input
													type="radio"
													name="addons[<?php echo $addonsSelle['option_id'] ?>]"
													id="addons_<?php echo $addonsSelle['option_id'] ?>_<?= $key ?>"
													value="<?php echo $readioValue->getId(); ?>"
													<?php if($requestAddon == $readioValue->getId()) { echo 'checked="checked"'; } ?>
													class="cls-to-add-to-wishlist"
													data-selector="optionsbooking[<?php echo $addonsSelle['option_id'] ?>]"
												/>
												<?php $valueTitle = $block->getBkHelperText()->showTranslateText($readioValue->getDropdownTitle(),$readioValue->getDropdownTitleTranslate()); ?>
												<span class="bk-addon-title"><?php echo $valueTitle; ?>
													<?php
													if ( $selectValue->getDropdownPrice() > 0 ) { echo ' +'.$block->getBkPriceHelper()->currency( $readioValue->getDropdownPrice(), true, false); }
													?>
										</span>
											</div>
										<?php endforeach; ?>
									<?php endif; ?>
								<?php elseif($addonsSelle->getOptionType() == 5) : ?>
									<?php $checkboxValues = $block->getBkOptionSelectValues($addonsSelle->getId()); ?>
									<?php if(count($checkboxValues)) : ?>
										<?php foreach($checkboxValues as $key => $checkboxValue) : ?>
											<div class="addons-input-item">
												<input
													type="checkbox"
													name="addons[<?php echo $addonsSelle['option_id'] ?>][]"
													id="addons_<?php echo $addonsSelle['option_id'] ?>_<?= $key ?>"
													value="<?php echo $checkboxValue->getId(); ?>"
													<?php if(is_array($requestAddon) && count($requestAddon) && in_array($checkboxValue->getId(),$requestAddon)) { echo 'checked="checked"'; } ?>
													class="cls-to-add-to-wishlist"
													data-selector="optionsbooking[<?php echo $addonsSelle['option_id'] ?>][<?= $checkboxValue->getId() ?>]"
												/>
												<?php $valueTitle = $block->getBkHelperText()->showTranslateText($checkboxValue->getDropdownTitle(),$checkboxValue->getDropdownTitleTranslate()); ?>
												<span class="bk-addon-title"><?php echo $valueTitle; ?>
													<?php
													if ( $checkboxValue->getDropdownPrice() > 0 ) { echo ' +'.$block->getBkPriceHelper()->currency( $checkboxValue->getDropdownPrice(), true, false); }
													?>
										</span>
											</div>
										<?php endforeach; ?>
									<?php endif; ?>
								<?php else : ?>
									<input
										class="txt-addons-item input-text <?php if($addonsSelle->getOptionRequired() == 1) echo 'required-empty'; ?> cls-to-add-to-wishlist"
										type="text"
										name="addons[<?php echo $addonsSelle->getId(); ?>]"
										id="addons_<?php echo $addonsSelle->getId(); ?>"
										value="<?php echo $requestAddon; ?>"
										data-selector="optionsbooking[<?php echo $addonsSelle['option_id'] ?>]"
									/>
								<?php endif; ?>
							</div>
						</dd>
					<?php endforeach; ?>
				</dl>
			</div>
		<?php endif; ?>
		<!--end Addons & Cross-sells-->
		<!-- hidden input -->
		<input type="hidden" id="temp-check-in" name="temp_check_in" value="<?php echo $request['temp_check_in']; ?>" />
		<input type="hidden" id="temp-check-in-two" name="temp_check_in_two" value="<?php echo $request['temp_check_in_two']; ?>" />
	</div>
	<div class="booking-book" style="float: left; width: 100%;">
<!--		<div class="booking-quantity">-->
<!--            <span>--><?php //echo __('Qty'); ?><!--</span>-->
<!--			<select name="qty" id="booking-qty">-->
<!--				--><?php //for($i = 1; $i <= $maxBooking; $i++ ) : ?>
<!--					<option --><?php //echo $request['qty'] == $i ? 'selected="selected"' : ''; ?><!-- value="--><?php //echo $i; ?><!--">--><?php //echo $i; ?><!--</option>-->
<!--				--><?php //endfor; ?>
<!--			</select>-->
<!--		</div>-->
		<!--default price-->
		<input type="hidden" name="magebay_base_product_price" id="magebay-base-product-price" value="0" />
		<input type="hidden" name="bookingsystem_total_price" id="bookingsystem-total-price" value="0" />
		<div class="booking-results">
		
		</div>
		<div class="booking-message-discount">
			<?php $discounts = $block->getBkDiscounts(); ?>
			<?php if(count($discounts)) : ?>
					<span class="discount-label"><b><?php echo __('Available discount for checkout:'); ?></b></span>
				<?php foreach($discounts as $discount) : ?>
					<?php if($discount['discount_type'] == '1') : ?>
						<span class="last-minute"><?php echo __('For reservations statring until %1 you get a %2 discount ',$discount['date_condition'],$discount['type_amount_text']); ?> <?php if($discount['discount_max_items'] > 0)  { echo __('for a maximum of %1 sessions',$discount['discount_max_items']); } ?></span>
					<?php elseif($discount['discount_type'] == '2') : ?>
						<span class="first-moment"><?php echo __('For reservations stating after %1 you get a %2 discount ',$discount['date_condition'],$discount['type_amount_text']); ?> <?php if($discount['discount_max_items'] > 0)  { echo __('for a maximum of %1 sessions',$discount['discount_max_items']); } ?></span>
					<?php else : ?>
						<span class="length-reservations"><?php echo __('For reservations of more than %1 sessions you get a %2 discount ',$discount['discount_period'],$discount['type_amount_text']); ?> <?php if($discount['discount_max_items'] > 0) { echo __('for a maximum of %1 sessions ',$discount['discount_max_items']); } ?></span>
					<?php endif; ?>
				<?php endforeach; ?>
			<?php endif; ?>
		</div>
		<?php 
//			if($request['action'] == 'configure')
//			{
//				echo $this->getLayout()->createBlock('Magento\Catalog\Block\Product\View')->setTemplate('Magebay_Bookingsystem::product/view/configure/updatecart.phtml')->toHtml();
//			}
//			else
//			{
//				echo $this->getLayout()->createBlock('Magento\Catalog\Block\Product\View')->setTemplate('Magebay_Bookingsystem::product/view/addtocart.phtml')->toHtml();
//			}
		?>
	</div>
</div>

