<?php
/**
 * @var $block \Magebay\Bookingsystem\Block\Booking;
 */
$enable = $block->getBkHelperDate()->getFieldSetting('bookingsystem/setting/enable');
/**
 * @var $helper \Daytours\Bookingsystem\Helper\Data
 */
$helper = $this->helper('Daytours\Bookingsystem\Helper\Data');
$isTransferProduct = $helper->ifCurrentProductIsTransfer();
if($enable == 1)
{
	$booking = $block->getBkProduct();
	if($booking && $booking->getBookingType() == 'per_day')
	{
		if($booking->getBookingTime() == 3)
		{
            if($isTransferProduct){
                echo $this->getLayout()->createBlock('Daytours\Bookingsystem\Block\Intervals')->setTemplate('Magebay_Bookingsystem::product/view/bk_form_intervals_transfer.phtml')->toHtml();
            }else{
                echo $this->getLayout()->createBlock('Magebay\Bookingsystem\Block\Intervals')->setTemplate('Magebay_Bookingsystem::product/view/bk_form_intervals.phtml')->toHtml();
            }

		}
		elseif ($block->getBkHelperDate()->checkStandardVersion() && $booking->getBookingTime() == 5)
        {
            echo $this->getLayout()->createBlock('Magebay\Bookingsystem\Block\Booking')->setTemplate('Magebay_Bookingsystem::product/view/bk_form_tour.phtml')->toHtml();
        }
		elseif($booking->getBookingTime() == 1 || $booking->getBookingTime() == 2  || $booking->getBookingTime() == 4)
		{
            if($isTransferProduct){
                echo $this->getLayout()->createBlock('Daytours\Bookingsystem\Block\Booking')->setTemplate('Magebay_Bookingsystem::product/view/bk_form_simple_transfer.phtml')->toHtml();
            }else{
                echo $this->getLayout()->createBlock('Magebay\Bookingsystem\Block\Booking')->setTemplate('Magebay_Bookingsystem::product/view/bk_form_simple.phtml')->toHtml();
            }
		}
	}
}
echo $this->getLayout()->createBlock('Magento\Catalog\Block\Product\View')->setTemplate('Magento_Catalog::product/view/addtocart-qty.phtml')->toHtml();
