<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<div class="admin__page-section-title">
    <strong class="title"><?php /* @escapeNotVerified */ echo $block->getHeaderText() ?></strong>
    <div class="actions">
        <?php echo $block->getButtonsHtml() ?>
    </div>
</div>
<?php echo $block->getChildHtml() ?>
<?php  /* Load Gird when chenage currency */ ?>
<?php echo $this->getLayout()->createBlock('Magebay\Bookingsystem\Block\Adminhtml\Order\Create\LoadGrid')->setTemplate('Magebay_Bookingsystem::sales/order/create/bk-grid.phtml')->toHtml(); ?>
