<?php $addonsSelles = $block->getAddonsSelles(); ?>
<?php $request = $block->getBookingRequest(); ?>
<?php if(count($addonsSelles)) : ?>
    <div class="addons-cross-sells">
        <dl>
            <?php foreach($addonsSelles as $addonsSelle) : ?>
                <?php $requestAddon =  isset($request['addons'][$addonsSelle->getId()]) ? $request['addons'][$addonsSelle->getId()] : ''; ?>
                <?php $addonRadioCheckoxClass = ''; ?>
                <?php if($addonsSelle->getOptionType() == 4 || $addonsSelle->getOptionType() == 5) :  ?>
                    <?php $addonRadioCheckoxClass = 'bk-addon-radio-checkbox';  ?>
                    <?php if($addonsSelle->getOptionRequired() == 1) { $addonRadioCheckoxClass .= ' required-empty'; } ?>
                <?php endif; ?>
                <dt>
                    <label for="addon-<?php echo $addonsSelle->getId(); ?>" <?php if ($addonsSelle->getOptionRequired() == 1) { echo 'class="required"'; } ?> >
                        <?php if ( $addonsSelle->getOptionRequired() == 1) { echo '<em>*</em>'; } ?>
                        <?php $title = $block->getBkHelperText()->showTranslateText($addonsSelle->getOptionTitle(),$addonsSelle->getOptionTitleTranslate()); ?>
                        <?php echo $title; ?>
                        <?php
                        if ( $addonsSelle->getOptionPrice() > 0 ) {
                            echo  '<span class="price-notice"> +<span class="price">'.$block->getBkPriceHelper()->currency($addonsSelle->getOptionPrice(), true, false).'</span></span>';
                        }
                        ?>
                    </label>
                </dt>
                <dd <?php if($addonRadioCheckoxClass != '') { ?>class="<?php echo $addonRadioCheckoxClass; ?>" id="bk-addon-radio-checkbox-<?php echo $addonsSelle->getId(); ?>"<?php } ?>>
                    <div class="addons-sells-item input-box">
                        <?php if($addonsSelle->getOptionType() == 2) : ?>
                            <select class="select-addons-item<?php if($addonsSelle->getOptionRequired() == 1) echo ' required-empty'; ?>" name="addons[<?php echo $addonsSelle['option_id'] ?>]">
                                <option value=""><?php echo __('Select Options'); ?></option>
                                <?php $selectValues = $block->getBkOptionSelectValues($addonsSelle->getId()); ?>
                                <?php if(count($selectValues)) : ?>
                                    <?php foreach($selectValues as $selectValue) : ?>
                                        <option value="<?php echo $selectValue->getId(); ?>" <?php if($requestAddon == $selectValue->getId()) { echo 'selected="selected"'; } ?>>
                                            <?php $valueTitle = $block->getBkHelperText()->showTranslateText($selectValue->getDropdownTitle(),$selectValue->getDropdownTitleTranslate()); ?>
                                            <?php echo $valueTitle; ?>
                                            <?php
                                            if ( $selectValue->getDropdownPrice() > 0 ) { echo ' +'.$block->getBkPriceHelper()->currency( $selectValue->getDropdownPrice(), true, false); }
                                            ?>
                                        </option>
                                    <?php endforeach; ?>
                                <?php endif; ?>
                            </select>
                        <?php elseif($addonsSelle->getOptionType() == 3) : ?>
                            <select multiple class="select-addons-item<?php if($addonsSelle->getOptionRequired() == 1) echo ' required-empty'; ?>" name="addons[<?php echo $addonsSelle['option_id'] ?>][]">
                                <?php $selectValues = $block->getBkOptionSelectValues($addonsSelle->getId()); ?>
                                <?php if(count($selectValues)) : ?>
                                    <?php foreach($selectValues as $selectValue) : ?>
                                        <option value="<?php echo $selectValue->getId(); ?>" <?php if(is_array($requestAddon) && count($requestAddon) && in_array($selectValue->getId(),$requestAddon)) { echo 'selected="selected"'; } ?>>
                                            <?php $valueTitle = $block->getBkHelperText()->showTranslateText($selectValue->getDropdownTitle(),$selectValue->getDropdownTitleTranslate()); ?>
                                            <?php echo $valueTitle; ?>
                                            <?php
                                            if ( $selectValue->getDropdownPrice() > 0 ) { echo ' +'.$block->getBkPriceHelper()->currency( $selectValue->getDropdownPrice(), true, false); }
                                            ?>
                                        </option>
                                    <?php endforeach; ?>
                                <?php endif; ?>
                            </select>
                        <?php elseif($addonsSelle->getOptionType() == 4) : ?>
                            <?php $readioValues = $block->getBkOptionSelectValues($addonsSelle->getId()); ?>
                            <?php if(count($readioValues)) : ?>
                                <?php foreach($readioValues as $readioValue) : ?>
                                    <div class="addons-input-item">
                                        <input type="radio" name="addons[<?php echo $addonsSelle['option_id'] ?>]" value="<?php echo $readioValue->getId(); ?>"  <?php if($requestAddon == $readioValue->getId()) { echo 'checked="checked"'; } ?>  />
                                        <?php $valueTitle = $block->getBkHelperText()->showTranslateText($readioValue->getDropdownTitle(),$readioValue->getDropdownTitleTranslate()); ?>
                                        <span class="bk-addon-title"><?php echo $valueTitle; ?>
                                            <?php
                                            if ( $selectValue->getDropdownPrice() > 0 ) { echo ' +'.$block->getBkPriceHelper()->currency( $readioValue->getDropdownPrice(), true, false); }
                                            ?>
										</span>
                                    </div>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        <?php elseif($addonsSelle->getOptionType() == 5) : ?>
                            <?php $checkboxValues = $block->getBkOptionSelectValues($addonsSelle->getId()); ?>
                            <?php if(count($checkboxValues)) : ?>
                                <?php foreach($checkboxValues as $checkboxValue) : ?>
                                    <div class="addons-input-item">
                                        <input type="checkbox" name="addons[<?php echo $addonsSelle['option_id'] ?>][]" value="<?php echo $checkboxValue->getId(); ?>"  <?php if(is_array($requestAddon) && count($requestAddon) && in_array($checkboxValue->getId(),$requestAddon)) { echo 'checked="checked"'; } ?>  />
                                        <?php $valueTitle = $block->getBkHelperText()->showTranslateText($checkboxValue->getDropdownTitle(),$checkboxValue->getDropdownTitleTranslate()); ?>
                                        <span class="bk-addon-title"><?php echo $valueTitle; ?>
                                            <?php
                                            if ( $checkboxValue->getDropdownPrice() > 0 ) { echo ' +'.$block->getBkPriceHelper()->currency( $checkboxValue->getDropdownPrice(), true, false); }
                                            ?>
										</span>
                                    </div>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        <?php else : ?>
                            <input class="txt-addons-item input-text <?php if($addonsSelle->getOptionRequired() == 1) echo 'required-empty'; ?>" type="text" name="addons[<?php echo $addonsSelle->getId(); ?>]" value="<?php echo $requestAddon; ?>" />
                        <?php endif; ?>
                    </div>
                </dd>
            <?php endforeach; ?>
        </dl>
    </div>
<?php endif; ?>