<?php 
/**
 * @Author      : Magebay Team
 * @package     Booking System Pro
 * @copyright   Copyright (c) 2014 MAGEBAY (http://www.magebay.com)
 * @terms  http://www.magebay.com/terms
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 **/
?>
<?php 
$bookingId = $block->getBookingId();
$bookingType = $block->getBookingType();
$bookingIdCalendarTwo = $block->getBookingIdCalendarTwo();

/**
 * @var $helper \Daytours\Bookingsystem\Helper\Data
 */
$helper = $this->helper('Daytours\Bookingsystem\Helper\Data');
$isTransferProduct = $helper->ifProductIsTransfer($bookingId);
?>
<?php $dataSend = array('booking_id'=>$bookingId, 'booking_type'=>$bookingType); ?>
<?php $dataSendCalendarTwo = array('booking_id'=>$bookingIdCalendarTwo, 'booking_type'=>$bookingType,'bookingIdCalendarTwo',$bookingIdCalendarTwo); ?>
<script>
	/*This variable is used to load the second calendar when you are seeing a transfer product, please doesn't erase */
	var intervalCalendar = null;
</script>
<div id="booking-light-box">
	<div class="booking-popup-content">

		<div class="clear"></div>
		<div class="popup-booking-left">
			<div id="booking-list-calendar-items" class="booking-table-items">
				<?php /* show items calendars */ ?>
				<?php echo $this->getLayout()->createBlock('Daytours\Bookingsystem\Block\Adminhtml\Calendars')->setData($dataSend)->setTemplate('Daytours_Bookingsystem::catalog/product/calendars/items.phtml')->toHtml(); ?>
			</div>
			<div class="clear"></div>
			<?php /* show gird calendars */ ?>
			<?php echo $this->getLayout()->createBlock('Daytours\Bookingsystem\Block\Adminhtml\Calendars')->setData($dataSend)->setTemplate('Daytours_Bookingsystem::catalog/product/calendars/calendar_grid.phtml')->toHtml(); ?>
		</div>
        <div class="popup-booking-right">
            <div id="form-booking-calendar">
            </div>
            <div class="popup-booking-intervals"></div>
        </div>
		<div class="clear"></div>

	<?php if( $isTransferProduct ) { ?>

		<!-- FILHO -->
		<div class="items-two">
			<div class="popup-booking-left">
				<div id="booking-list-calendar-items-two" class="booking-table-items">
					<?php /* show items calendars */ ?>
					<?php echo $this->getLayout()->createBlock('Daytours\Bookingsystem\Block\Adminhtml\Calendars')->setData($dataSend)->setTemplate('Daytours_Bookingsystem::catalog/product/calendars/items_calendar_two.phtml')->toHtml(); ?>
				</div>
				<div class="clear"></div>
				<?php /* show gird calendars */ ?>
				<?php echo $this->getLayout()->createBlock('Daytours\Bookingsystem\Block\Adminhtml\Calendars')->setData($dataSend)->setTemplate('Daytours_Bookingsystem::catalog/product/calendars/calendar_grid_two.phtml')->toHtml(); ?>
			</div>
			<div class="popup-booking-right">
				<div id="form-booking-calendar-two">
				</div>
				<div class="popup-booking-intervals-two"></div>
			</div>
			<div class="clear"></div>
		</div>
		<!-- END FILHO -->
	<?php } ?>
	</div>
	<div class="clear"></div>
</div>
	

