<?php if($block->checkIsLogin()){ ?>
    <?php if ( $block->checkIsSeller() ) { ?>
        <li>
            <a href="<?php echo $this->getUrl('marketplace/seller/dashboard'); ?>" ><?php echo __("Seller Dashboard"); ?></a>
        </li>
    <?php } else { ?>
        <li>
            <a href="<?php echo $this->getUrl('marketplace/seller/become'); ?>" ><?php echo __("Register Seller Account"); ?></a>
        </li>
    <?php } ?>
<?php } ?>