<div class="important">
    <div class="important-content">
        <p><b>IMPORTANT:</b> Last minute bookings requests are subject to emergency service. The client must make a pre-payment by credit card to confirm the reservation. In case the chose activity is finally not available a refund of the amount will de made</p>
        <br/>
        <p>Please not final confirmation may take more than 30 minutes. For more info please view our <a href="#">Terms &amp; Conditions</a></p>
    </div>
</div>