
<?php

/**
 * @var \Daytours\Catalog\Block\SubTotales $block
 */
?>

<div class="sub-total sub-total-price-regular hide">
    <strong class="title"><?= __('Sub-total:') ?></strong>
    <div class="sub-total-content">
<!--        <p style="display: none;"><b>Adults:</b> <span>US$1557 x 2</span></p>-->
<!--        <p style="display: none;"><b>Childs:</b> <span>US$1000 x 1</span></p>-->
<!--        <p style="display: none;"><b>Infants:</b> <span>US$0 x 1</span></p>-->
    </div>
</div>