<?php
/**
 * @copyright Copyright © 2019 Onetree. All rights reserved.
 * @author    Hector Perez Hernandez <hector.perez@onetree.com>
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Framework\View\Element\Template $block */
?>
<div class="product-share-popup" style="display: none;">
    <span class="btn-close-popup close-background"></span>
    <div class="product-share-wrapper">
        <div class="popup-head-share"></div>
        <span class="btn-close-popup close-button"></span>
        <h3 class="title"><?= __('Share with friends') ?></h3>
        <!--div class="addthis_inline_share_toolbox"></div-->
    </div>
</div>
