<?php

namespace Daytours\Provider\Model\ResourceModel;

use Magento\Framework\Exception\AlreadyExistsException;
use Magento\Framework\Model\ResourceModel\Db\AbstractDb as AbstractDbAlias;

class Provider extends AbstractDbAlias
{

    protected function _construct()
    {
        $this->_init('booking_provider','entity_id');
    }

    protected function _beforeSave(\Magento\Framework\Model\AbstractModel $object)
    {
        if( is_null($object->getId()) ){
            $connection = $this->getConnection();
            $bind = ['email' => $object->getEmail()];
            $select = $connection->select()->from(
                $this->getMainTable(),
                [$this->getIdFieldName()]
            )->where(
                'email = :email'
            );

            $result = $connection->fetchOne($select, $bind);
            if ($result) {
                throw new AlreadyExistsException(
                    __('A Provider with the same email already exists.')
                );
            }
        }

        return parent::_beforeSave($object); // TODO: Change the autogenerated stub
    }

}