<?php
/**
 * @category FishPig
 * @package FishPig_WordPress
 * @notes This template is used when there post/list.phtml doesn't have a child block called 'renderer'
 * @notes This happens when post/list.phtml is called in via PHP rather than via the default layout handles
 */
?>
<?php if ($post = $this->getPost()): ?>
	<div class="post-list-item">
        <?php $image = $post->getImage(); ?>
        <?php $categoryString = $post->getTermCollectionAsString('one_category'); ?>
		<?php if (isset($image) && $image) { ?>
        <div class="post-image" style="background-image: url('<?php echo $image->getData('guid') ?>')">
            <a class="link-post" href="<?php echo $post->getUrl() ?>"></a>
            <a class="tag-post rdj4u-reviews" href="<?php echo $categoryString['url']; ?>"><?php echo $categoryString['name']; ?></a>
        </div>
		<?php } ?>
        <div class="post-date">
            <span class="date-icon"><img src="<?php echo $this->getViewFileUrl('images/icon-date.png') ?>"/><i><?php echo $post->getPostDate() ?></i></span>
        </div>
        <h3 class="post-title">
            <a href="<?php echo $post->getUrl() ?>">
                <?php echo $this->escapeHtml($post->getName()) ?>
            </a>
        </h3>
        <div class="post-short-description">
            <?php echo $post->getExcerpt(40) ?>
        </div>
        <a class="post-read" href="<?php echo $post->getUrl() ?>"><?= __("Read more") ?></a>
	</div>
<?php endif; ?>