<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php if ($crumbs && is_array($crumbs)) : ?>
<div class="breadcrumbs">
    <ul class="items">
        <?php $i = 0; ?>
        <?php foreach ($crumbs as $crumbName => $crumbInfo) : $i++; ?>
            <?php
            $cssPreLastToProductpage = '';
            if( array_key_exists('product',$crumbs) && $i == count($crumbs) -1 ){
                $cssPreLastToProductpage = ' pre-last-element';
            }
            ?>
            <li class="item <?= /* @escapeNotVerified */ $crumbName . $cssPreLastToProductpage ?> ">
            <?php if ($crumbInfo['link']) : ?>
                <a href="<?= /* @escapeNotVerified */ $crumbInfo['link'] ?>" title="<?= $block->escapeHtml($crumbInfo['title']) ?>"><?= $block->escapeHtml($crumbInfo['label']) ?></a>
            <?php elseif ($crumbInfo['last']) : ?>
                <strong><?= $block->escapeHtml($crumbInfo['label']) ?></strong>
            <?php else: ?>
                <?= $block->escapeHtml($crumbInfo['label']) ?>
            <?php endif; ?>
            </li>
        <?php endforeach; ?>
    </ul>
</div>
<?php endif; ?>
