<?php
/**
* @Author      : haunv + kien
* @package     Marketplace
* @copyright   Copyright (c) 2016 MAGEBAY (http://www.magebay.com)
* @terms  http://www.magebay.com/terms
* @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
**/
?>
<?php $_sellerInfomation=$block->getSellerInfomation() ?>
<div class="block block-maketplace-profile">
	<div class="block-content">
		<form id="form-edit-profile-seller-id" class="form form-edit-profile-seller" method="post" enctype="multipart/form-data" action="<?php /* @escapeNotVerified */ echo $block->getUrl('marketplace/seller/editPost') ?>" >
			<fieldset class="fieldset info">
                <input type="hidden" name="seller[sellerId]" value="<?php echo $_sellerInfomation['id'] ?>" />
    			<?php echo $block->getBlockHtml('formkey')?>
    			<legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Profile Information') ?></span></legend>
				<div class="field row storetitle">
					<label class="label" for="storetitle"><span><?php /* @escapeNotVerified */ echo __('Store Title') ?></span><span style="color: red;"> * </span></label>
					<div class="control">
						<input type="text" data-validate="{required:true}" name="seller[storetitle]" id="storetitle" title="<?php /* @escapeNotVerified */ echo __('Store Title') ?>" class="input-text admin__control-text" value="<?php echo $_sellerInfomation['storetitle'] ?>" />
					</div>				
				</div>
				<div class="field row storeurl">
					<label class="label" for="storeurl"><span><?php /* @escapeNotVerified */ echo __('Store Url') ?></span><span style="color: red;"> * </span></label>
					<div class="control">
						<input type="text" data-validate="{required:true}" name="seller[storeurl]" id="storeurl" title="<?php /* @escapeNotVerified */ echo __('Store Url') ?>" class="input-text admin__control-text" value="<?php echo $_sellerInfomation['storeurl'] ?>" />
					</div>				
				</div>
				<div class="field row company">
					<label class="label"><span><?php /* @escapeNotVerified */ echo __('Company') ?></span></label>
					<div class="control">
						<input type="text" name="seller[company]" id="company" title="<?php /* @escapeNotVerified */ echo __('Company') ?>" class="input-text admin__control-text" value="<?php echo $_sellerInfomation['company'] ?>" />
					</div>
				</div>
				<div class="field row bannerimg">
					<label class="label" for="bannerimg"><span><?php /* @escapeNotVerified */ echo __('Company Banner') ?></span></label>
					<div class="control">
						<input type="file" id="bannerimg" name="seller[bannerimg]" title="<?php /* @escapeNotVerified */ echo __('Banner Pic') ?>" class="input-text banner admin__control-text" size="26" />					
						<?php if($_sellerInfomation['bannerimg']){ 
							$_urlImage=$block->getUrlImage($_sellerInfomation['bannerimg']);
						?>
							<div class="block block-image">
								<img src="<?php echo $_urlImage ?>" title="" alt="" /><br />
								<input type="checkbox" id="bannerimg_delete" value="1" name="seller[bannerimg_delete]" />
								<label class="label" for="bannerimg_delete"><?php /* @escapeNotVerified */ echo __('Delete Banner Image') ?></label>
								<input type="hidden" name="seller[bannerimg_value]" value="<?php echo $_sellerInfomation['bannerimg'] ?>" />
							</div>
						<?php } ?>
					</div>
				</div>
				<div class="field row logoimg">
					<label class="label" for="logoimg"><span><?php /* @escapeNotVerified */ echo __('Company Logo') ?></span></label>
					<div class="control">
						<input type="file" id="logoimg" name="seller[logoimg]" title="<?php /* @escapeNotVerified */ echo __('Logo Pic') ?>" class="input-text logoimg admin__control-text" size="26" />					
						<?php if($_sellerInfomation['logoimg']){ 
							$_urlImage=$block->getUrlImage($_sellerInfomation['logoimg']);
						?>
							<div class="block block-image">
								<img src="<?php echo $_urlImage ?>" title="" alt="" /><br />
								<input type="checkbox" value="1" id="logoimg_delete" name="seller[logoimg_delete]" />
								<label class="label" for="logoimg_delete"><?php /* @escapeNotVerified */ echo __('Delete Logo Image') ?></label>
								<input type="hidden" name="seller[logoimg_value]" value="<?php echo $_sellerInfomation['logoimg'] ?>" />
							</div>
						<?php } ?>					
					</div>
				</div>
				<div class="field row short_description">
					<label class="label"><span><?php /* @escapeNotVerified */ echo __('Short Description') ?></span></label>
					<div class="control">
						<textarea name='seller[short_description]' title='<?php /* @escapeNotVerified */ echo __('Short Description') ?>' id='short_description' class='input-text compdesi wysiwyg-editor' ><?php echo $_sellerInfomation['short_description'] ?></textarea>
					</div>
				</div>		
				<div class="field row description">
					<label class="label"><span><?php /* @escapeNotVerified */ echo __('Description') ?></span></label>
					<div class="control">
						<textarea name='seller[description]' title='<?php /* @escapeNotVerified */ echo __('Description') ?>' id='description' class='input-text compdesi wysiwyg-editor' ><?php echo $_sellerInfomation['description'] ?></textarea>
					</div>
				</div>			
				<div class="field row returnpolicy">
					<label class="label"><span><?php /* @escapeNotVerified */ echo __('Return Policy') ?></span></label>
					<div class="control">
						<textarea name='seller[returnpolicy]' title='<?php /* @escapeNotVerified */ echo __('Return Policy') ?>' id='returnpolicy' class='input-text compdesi wysiwyg-editor' ><?php echo $_sellerInfomation['returnpolicy'] ?></textarea>
					</div>
				</div>			
				<div class="field row shippingpolicy">
					<label class="label"><span><?php /* @escapeNotVerified */ echo __('Shipping Policy') ?></span></label>
					<div class="control">
						<textarea name='seller[shippingpolicy]' title='<?php /* @escapeNotVerified */ echo __('Shipping Policy') ?>' id='shippingpolicy' class='input-text compdesi wysiwyg-editor' ><?php echo $_sellerInfomation['shippingpolicy'] ?></textarea>
					</div>
				</div>
				<div class="field row contactnumber">
					<label class="label" for="contactnumber"><span><?php /* @escapeNotVerified */ echo __('Contact Number') ?></span></label>
					<div class="control">
						<input type="text" name="seller[contactnumber]" id="contactnumber" title="<?php /* @escapeNotVerified */ echo __('Contact Number') ?>" class="input-text admin__control-text" value="<?php echo $_sellerInfomation['contactnumber'] ?>" />
					</div>
				</div>
				<?php 
					$moduleManager = \Magento\Framework\App\ObjectManager::getInstance()->create('Magento\Framework\Module\Manager');	
					if($moduleManager->isEnabled('Magebay_PaypalAdaptive')){
				?>
						<div class="field row paymentsource">
							<label class="label" for="paymentsource"><span><?php /* @escapeNotVerified */ echo __('Paypal Payment info') ?></span><span style="color: red;"> * </span></label>
							<div class="control">
								<textarea name="seller[paymentsource]" id="paymentsource" title="<?php /* @escapeNotVerified */ echo __('Paypal Payment info') ?>" class="input-text compdesi" data-validate="{required:true, 'validate-email':true}"><?php echo $_sellerInfomation['paymentsource'] ?></textarea>
							</div>
						</div>
				<?php } ?>											
				<div class="field row address">
					<label class="label"><span><?php /* @escapeNotVerified */ echo __('Address') ?></span></label>
					<div class="control">
						<input type="text" name="seller[address]" id="address" title="<?php /* @escapeNotVerified */ echo __('Address') ?>" class="input-text admin__control-text" value="<?php echo $_sellerInfomation['address'] ?>" />
					</div>
				</div> 
				<div class="field row city">
					<label class="label"><span><?php /* @escapeNotVerified */ echo __('City') ?></span></label>
					<div class="control">
						<input type="text" name="seller[city]" id="city" title="<?php /* @escapeNotVerified */ echo __('City') ?>" class="input-text admin__control-text" value="<?php echo $_sellerInfomation['city'] ?>" />
					</div>
				</div>  
				<div class="field row zipcode">
					<label class="label"><span><?php /* @escapeNotVerified */ echo __('Zipcode') ?></span></label>
					<div class="control">
						<input type="text" name="seller[zipcode]" id="zipcode" title="<?php /* @escapeNotVerified */ echo __('Zipcode') ?>" class="input-text admin__control-text" value="<?php echo $_sellerInfomation['zipcode'] ?>" />
					</div>
				</div>           
				<div class="field row country">
					<label class="label"><span><?php /* @escapeNotVerified */ echo __('Country') ?></span></label>
					<div class="control">
						<select id="country" name="seller[country]" title="<?php /* @escapeNotVerified */ echo __('Country') ?>">
							<option disabled="disabled" selected="selected" value=""><?php /* @escapeNotVerified */ echo __('Select Country') ?></option>
							<?php
							$_countries=$block->_getOptionsCountry();
							foreach($_countries as $k=>$_countryitem){						
								if(!$k) continue;
								if($_countryitem['value']==$_sellerInfomation['country']){
							?>						
									<option value="<?php echo $_countryitem['value']?>" selected="selected" ><?php echo $_countryitem['label']?></option>
								<?php }else{ ?>
									<option value="<?php echo $_countryitem['value']?>"><?php echo $_countryitem['label']?></option>
								<?php } ?>
							<?php } ?>
						</select>
					</div>
				</div>
				<div class="field row metakeywords">
					<label class="label"><span><?php /* @escapeNotVerified */ echo __('Meta Keywords') ?></span></label>
					<div class="control">
						<textarea name="seller[meta_keyword]" id="meta_keyword" title="<?php /* @escapeNotVerified */ echo __('Meta Keywords') ?>" class="input-text compdesi"><?php echo $_sellerInfomation['meta_keyword'] ?></textarea>
					</div>
				</div>						
				<div class="field row metadescription">
					<label class="label"><span><?php /* @escapeNotVerified */ echo __('Meta Description') ?></span></label>
					<div class="control">
						<textarea name="seller[meta_description]" id="meta_description" title="<?php /* @escapeNotVerified */ echo __('Meta Description') ?>" class="input-text compdesi"><?php echo $_sellerInfomation['meta_description'] ?></textarea>
					</div>
				</div>
				<div class="field row facebookid">
					<label class="label" for="facebookid"><span><?php /* @escapeNotVerified */ echo __('Facebook ID') ?></span></label>				
					<div class="control">
						<input type="text" name="seller[facebookid]" id="facebookid" title="<?php /* @escapeNotVerified */ echo __('Facebook ID') ?>" class="input-text admin__control-text" value="<?php echo $_sellerInfomation['facebookid'] ?>" />
					</div>
				</div>
				<div class="field row twitterid">
					<label class="label" for="twitterid"><span><?php /* @escapeNotVerified */ echo __('Twitter ID') ?></span></label>				
					<div class="control">
						<input type="text" name="seller[twitterid]" id="twitterid" title="<?php /* @escapeNotVerified */ echo __('Twitter ID') ?>" class="input-text admin__control-text" value="<?php echo $_sellerInfomation['twitterid'] ?>" />
					</div>
				</div>
				<div class="field row instagram_url">
					<label class="label" for="instagram_url"><span><?php /* @escapeNotVerified */ echo __('Instagram Url') ?></span></label>				
					<div class="control">
						<input type="text" name="seller[instagram_url]" id="instagram_url" title="<?php /* @escapeNotVerified */ echo __('Instagram Url') ?>" class="input-text admin__control-text" value="<?php echo $_sellerInfomation['instagram_url'] ?>" />
					</div>
				</div>
				<div class="field row google_plus">
					<label class="label" for="google_plus"><span><?php /* @escapeNotVerified */ echo __('Google Plus Url') ?></span></label>				
					<div class="control">
						<input type="text" name="seller[google_plus]" id="google_plus" title="<?php /* @escapeNotVerified */ echo __('Google Plus Url') ?>" class="input-text admin__control-text" value="<?php echo $_sellerInfomation['google_plus'] ?>" />
					</div>
				</div>
				<div class="field row youtube_url">
					<label class="label" for="youtube_url"><span><?php /* @escapeNotVerified */ echo __('Youtube Url') ?></span></label>				
					<div class="control">
						<input type="text" name="seller[youtube_url]" id="youtube_url" title="<?php /* @escapeNotVerified */ echo __('Youtube Url') ?>" class="input-text admin__control-text" value="<?php echo $_sellerInfomation['youtube_url'] ?>" />
					</div>
				</div>
				<div class="field row pinterest_url">
					<label class="label" for="pinterest_url"><span><?php /* @escapeNotVerified */ echo __('Pinterest Url') ?></span></label>				
					<div class="control">
						<input type="text" name="seller[pinterest_url]" id="pinterest_url" title="<?php /* @escapeNotVerified */ echo __('Pinterest Url') ?>" class="input-text admin__control-text" value="<?php echo $_sellerInfomation['pinterest_url'] ?>" />
					</div>
				</div>
				<div class="field row vimeo_url">
					<label class="label" for="vimeo_url"><span><?php /* @escapeNotVerified */ echo __('Vimeo Url') ?></span></label>				
					<div class="control">
						<input type="text" name="seller[vimeo_url]" id="vimeo_url" title="<?php /* @escapeNotVerified */ echo __('Vimeo Url') ?>" class="input-text admin__control-text" value="<?php echo $_sellerInfomation['vimeo_url'] ?>" />
					</div>
				</div>
				<?php if($moduleManager->isEnabled('Magebay_SellerAttributeManagement')){ ?>
        			<?php 
        			$value_attribute = \Magento\Framework\App\ObjectManager::getInstance()->create('\Magebay\SellerAttributeManagement\Model\SellerAttributeValue')->getCollection()->addFieldToFilter('seller_id', $_sellerInfomation['user_id'])->getFirstItem();
        			$value = unserialize($value_attribute->getValue());
        			$data_attribute = \Magento\Framework\App\ObjectManager::getInstance()->create('\Magebay\SellerAttributeManagement\Model\SellerAttributeManagement')->getCollection()->addFieldToFilter('status', 1)->setOrder('sort_order','ASC');
        			if ( count($data_attribute) > 0 ) {
        			?>
                        <div class="section-entry" >
        					<div class="section-head" >
                                <strong><?php  echo __('Attribute Information') ?></strong>
        					</div>
        					<div class="section-content"  >
        						<div class="section-fieldset" >
                        			<?php
                                        foreach($data_attribute as $attribute){
                                    ?>
                            			<div class="field row <?php echo $attribute['attribute_code']?>">
                            				<label class="label" for="<?php echo $attribute['attribute_code']?>">
                                                <?php if($attribute['required']){ ?>
                                                        <span><?php echo $attribute['default_label']?></span>
                                                        <span style="color: red;"> * </span>
                                                <?php }else{ ?>
                                                    <span><?php echo $attribute['default_label']?></span>
                                                <?php } ?>
                                            </label>
                            				<div class="control">
                                                <?php 
                                                    switch ($attribute['input_type']){ 
                                                        case 'text' :
                                                ?>
                                                            <input type="text" <?php if($attribute['required']){ ?> data-validate="{required:true}" <?php } ?> id="<?php echo $attribute['attribute_code']?>" class="input-text admin__control-text" name="attribute[<?php echo $attribute['attribute_code']?>]" title="<?php echo $attribute['default_label']?>" value="<?php echo @$value[$attribute['attribute_code']]?>" />
                                				<?php
                                                        break ;
                                                        case 'textarea' :
                                                ?>
                                                            <textarea <?php if($attribute['required']){ ?> data-validate="{required:true}" <?php } ?> id="<?php echo $attribute['attribute_code']?>" class="input-text compdesi" name="attribute[<?php echo $attribute['attribute_code']?>]" title="<?php echo $attribute['default_label']?>"><?php echo @$value[$attribute['attribute_code']]?></textarea>
                                                <?php
                                                        break;
                                                        case 'date' :
                                                ?>
                                                            <input type="text" <?php if($attribute['required']){ ?> data-validate="{required:true}" <?php } ?> id="<?php echo $attribute['attribute_code']?>" class="input-text admin__control-text" name="attribute[<?php echo $attribute['attribute_code']?>]" title="<?php echo $attribute['default_label']?>" value="<?php echo @$value[$attribute['attribute_code']]?>" style="width: 100%;" />
                                                            <script>
                                                                require([
                                                                    "jquery",
                                                                    "mage/mage",
                                                                    "mage/calendar"
                                                                ], function($){
                                                                    $("#<?php echo $attribute['attribute_code']?>").calendar({'dateFormat':'mm/dd/yy'});
                                                                });
                                                            </script>
                                                <?php
                                                        break;
                                                        case 'boolean' :
                                                ?>			
                                        					<select <?php if($attribute['required']){ ?> data-validate="{required:true}" <?php } ?> id="<?php echo $attribute['attribute_code']?>" name="attribute[<?php echo $attribute['attribute_code']?>]" title="<?php echo $attribute['default_label']?>">
                                                                <option value="YES" <?php echo @$value[$attribute['attribute_code']]=='YES'?'selected=""':''?>><?php echo __('YES') ?></option>
                                                                <option value="NO"  <?php echo @$value[$attribute['attribute_code']]=='NO'?'selected=""':''?>><?php echo __('NO') ?></option>
                                                            </select>
                                                <?php
                                                        break;
                                                        case 'multiselect' :
                                                ?>
                                                            <select multiple <?php if($attribute['required']){ ?> data-validate="{required:true}" <?php } ?> id="<?php echo $attribute['attribute_code']?>" name="attribute[<?php echo $attribute['attribute_code']?>[]]" title="<?php echo $attribute['default_label']?>">
                                                                <?php 
                                                                    $option = unserialize($attribute['option_label']); 
                                                                    if($option){
                                                                        foreach($option as $op){
                                                                ?>
                                                                            <option value="<?php echo $op ?>" <?php echo @in_array($op,@$value[$attribute['attribute_code']])?'selected=""':''?>><?php echo $op ?></option>
                                                                <?php
                                                                        }
                                                                    }
                                                                ?>
                                                            </select>
                                                <?php
                                                        break;
                                                        case 'select' :
                                                ?>
                                                            <select <?php if($attribute['required']){ ?> data-validate="{required:true}" <?php } ?> id="<?php echo $attribute['attribute_code']?>" name="attribute[<?php echo $attribute['attribute_code']?>]" title="<?php echo $attribute['default_label']?>">
                                                                <?php 
                                                                    $option = unserialize($attribute['option_label']); 
                                                                    if($option){
                                                                        foreach($option as $op){
                                                                ?>
                                                                            <option value="<?php echo $op ?>" <?php echo @$value[$attribute['attribute_code']]==$op?'selected=""':''?>><?php echo $op ?></option>
                                                                <?php
                                                                        }
                                                                    }
                                                                ?>
                                                            </select>
                                                <?php
                                                        break;
                                                        case 'price' :
                                                ?>
                                                            <div class="admin__control-addon">
                                                                <input type="text" <?php if($attribute['required']){ ?> data-validate="{required:true}" <?php } ?> id="<?php echo $attribute['attribute_code']?>" class="admin__control-text" name="attribute[<?php echo $attribute['attribute_code']?>]" title="<?php echo $attribute['default_label']?>" value="<?php echo @$value[$attribute['attribute_code']]?>" />
                                                                <label class="admin__addon-prefix" for="<?php echo $attribute['attribute_code']?>">
                                                                    <span>$</span>
                                                                </label>
                                                            </div>
                                                <?php
                                                        break;
                                                        case 'media_image' :
                                                ?>
                                                            <input type="file" <?php if($attribute['required'] && !@$value[$attribute['attribute_code']]){ ?> data-validate="{required:true}" <?php } ?> id="<?php echo $attribute['attribute_code']?>" class="input-text banner admin__control-text" name="attribute[<?php echo $attribute['attribute_code']?>]" title="<?php echo $attribute['default_label']?>" size="26" />
                                                            <?php if(@$value[$attribute['attribute_code']]){ 
                                        						$_urlImage=$block->getUrlImage(@$value[$attribute['attribute_code']]);
                                        					?>
                                            					<div class="block block-image">
                                            						<img src="<?php echo $_urlImage ?>" title="" alt="" /><br />
                                            						<input type="checkbox" id="<?php echo $attribute['attribute_code']?>_delete" value="1" name="attribute[<?php echo $attribute['attribute_code']?>_delete]" />
                                            						<label class="label" for="<?php echo $attribute['attribute_code']?>_delete"><?php /* @escapeNotVerified */ echo __('Delete Image') ?></label>
                                            						<input type="hidden" name="attribute[<?php echo $attribute['attribute_code']?>_value]" value="<?php echo @$value[$attribute['attribute_code']] ?>" />
                                            					</div>
                                        					<?php } ?>
                                                <?php
                                                        break;
                                                    } 
                                                ?>
                                            </div>				
                            			</div>
                                    <?php } ?>
                                </div>
        					</div>
                        </div>
                    <?php } ?>
                <?php } ?>
    			<div class="field row block-button">
					<label class="label"> &nbsp </label>
    				<div class="control">
						<button type="submit" id="save-button" title="<?php  echo __('Save Profile') ?>">
							<span><span><?php echo __('Save Profile') ?></span></span>
						</button>
					</div>	
    			</div>
            </fieldset>
		</form>
	</div>
</div>
<script>
	require(['jquery','mage/mage'],function($){
		var dataFormProfile = $('#form-edit-profile-seller-id');
		var ignore = null;
		dataFormProfile.mage('validation', {
			ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
		}).find('input:text').attr('autocomplete', 'off');
        
        var dataFormAttribute = $('#form-edit-attribute-seller-id');
		var ignore = null;
		dataFormAttribute.mage('validation', {
			ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
		}).find('input:text').attr('autocomplete', 'off');
	});
</script>
<script>
    require([
    	'jquery',
    	'mage/adminhtml/wysiwyg/tiny_mce/setup'
    ], function(jQuery){
    	var config = '',
    		editor;
    	jQuery.extend(config, {
    		settings: {
    			theme_advanced_buttons1 : 'bold,italic,|,justifyleft,justifycenter,justifyright,|,' +
    				'fontselect,fontsizeselect,|,forecolor,backcolor,|,link,unlink,image,|,bullist,numlist,|,code',
    			theme_advanced_buttons2: null,
    			theme_advanced_buttons3: null,
    			theme_advanced_buttons4: null,
    			theme_advanced_statusbar_location: null
    		},
    		files_browser_window_url: false
    	});
    
    	editor = new tinyMceWysiwygSetup(
    		'description',
    		config
    	);
    	editor.turnOn();
    	jQuery('#description')
    	.addClass('wysiwyg-editor')
    	.data(
    		'wysiwygEditor',
    		editor
    	);
        
    	editor = new tinyMceWysiwygSetup(
    		'returnpolicy',
    		config
    	);
    	editor.turnOn();
    	jQuery('#returnpolicy')
    	.addClass('wysiwyg-editor')
    	.data(
    		'wysiwygEditor',
    		editor
    	);
    
    	editor = new tinyMceWysiwygSetup(
    		'shippingpolicy',
    		config
    	);
    	editor.turnOn();
    	jQuery('#shippingpolicy')
    	.addClass('wysiwyg-editor')
    	.data(
    		'wysiwygEditor',
    		editor
    	);
    });
</script>