<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php /* @var $block \Magento\Catalog\Block\Adminhtml\Product\Composite\Fieldset\Options */ ?>
<?php $id = $this->getRequest()->getParam('id',0); ?>
<?php if($id > 0) : ?>
	<?php echo $this->getLayout()->createBlock('Magebay\Bookingsystem\Block\Adminhtml\Order\Create')->setBookingId($id)->setTemplate('Magebay_Bookingsystem::sales/order/create.phtml')->toHtml();  ?>
<?php endif; ?>
<?php $options = $block->decorateArray($block->getOptions()); ?>
<?php if (count($options)): ?>

<?php echo $block->getChildHtml('options_js') ?>

<fieldset id="product_composite_configure_fields_options" class="fieldset admin__fieldset <?php echo $block->getIsLastFieldset() ? 'last-fieldset' : '' ?>">
    <legend class="legend admin__legend">
        <span><?php /* @escapeNotVerified */ echo __('Custom Options') ?></span>
    </legend><br>
    <?php foreach ($options as $option): ?>
        <?php echo $block->getOptionHtml($option); ?>
    <?php endforeach;?>
</fieldset>

<?php endif; ?>
