<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var \Magento\Sales\Block\Adminhtml\Order\View\Items\Renderer\DefaultRenderer $block */ ?>
<?php $_item = $block->getItem() ?>
<?php $block->setPriceDataObject($_item) ?>
<?php $trProduct = ''; ?>
<tr>
    <?php $i = 0;
    $columns = $block->getColumns();
    $lastItemNumber = count($columns) ?>
    <?php foreach ($columns as $columnName => $columnClass):?>
        <?php $i++; ?>
        <?php if($i > 1) :?>
            <td class="<?= /* @noEscape */ $columnClass ?><?= /* @noEscape */ ($i === $lastItemNumber ? ' last' : '') ?>">
                <?= /* @escapeNotVerified */ $block->getColumnHtml($_item, $columnName) ?>
            </td>
        <?php else: ?>
            <?php $trProduct =  $block->getColumnHtml($_item, $columnName) ?>
        <?php endif; ?>
    <?php endforeach; ?>
</tr>
<tr>
    <td colspan="<?=  $i ?>">
        <?= $trProduct ?>
    </td>
</tr>