<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var  $block \Magento\Sales\Block\Order\Item\Renderer\DefaultRenderer */
$_item = $block->getItem();
$orderHelper = $this->helper('Daytours\Sales\Helper\Data');
?>

<div class="print-row product-title-price">
    <div class="print-col-sm-9 ">
        <?= $block->escapeHtml($_item->getName()) ?>
    </div>
    <div class="print-col-sm-3 text-align-right">
        <?= $block->getItemRowTotalHtml() ?>
    </div>
</div>
<div class="print-row product-details-options">
    <div class="print-col-sm-12">
        <?php if ($_options = $block->getItemOptions()): ?>
            <dl class="item-options">
                <?php $regularService = ''; ?>
                <?php foreach ($_options as $_option) : ?>

                    <?php if($_option['label'] == 'regular_services'): ?>
                        <?php $regularService = $_option['value']; ?>
                    <?php else: ?>
                        <dt><?= $block->escapeHtml($_option['label']) ?></dt>
                        <?php if (!$block->getPrintStatus()): ?>
                            <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                            <dd>
                                <?php if (isset($_formatedOptionValue['full_view'])): ?>
                                    <?= /* @escapeNotVerified */ $_formatedOptionValue['full_view'] ?>
                                <?php else: ?>
                                    <?= /* @escapeNotVerified */ $_formatedOptionValue['value'] ?>
                                <?php endif; ?>
                            </dd>
                        <?php else: ?>
                            <dd>
                                <?= nl2br($block->escapeHtml((isset($_option['print_value']) ? $_option['print_value'] : $_option['value']))) ?>
                            </dd>
                        <?php endif; ?>
                    <?php endif; ?>
                <?php endforeach; ?>
                <div class="clear clearfix"></div>
                <?php
                if( !empty($regularService) ){
                    echo '<dl class="item-options">';
                    $regularService = json_decode($regularService);
                    foreach ($regularService as $itemR){
                        echo '<dt><strong><em>'.$itemR->label.'</em></strong></dt>';
                        echo '<dd><span class="price-item">'.$itemR->price.'</span> </span><span class="qty-item"> x '.$itemR->qty.'</span></dd>';
                    }
                    echo "</dl>";
                }
                ?>
            </dl>
        <?php endif; ?>
        <?php $addtInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addtInfoBlock) :?>
            <?= $addtInfoBlock->setItem($_item)->toHtml() ?>
        <?php endif; ?>
        <?= $block->escapeHtml($_item->getDescription()) ?>
    </div>
    <div class="clear-both-print"></div>
</div>
