<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/**
 * Currency switcher
 *
 * @var \Magento\Directory\Block\Currency $block
 */

?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$currencysymbol= $objectManager
    ->get('Magento\Store\Model\StoreManagerInterface');
$currencyCodeBase = $currencysymbol->getStore()->getCurrentCurrencyCode();
$currency  = $objectManager
    ->create('Magento\Directory\Model\CurrencyFactory')
    ->create()->load($currencyCodeBase);
$currencySymbol= $currency->getCurrencySymbol();
?>
<?php if ($block->getCurrencyCount() >= 1): ?>
    <?php $currencies = $block->getCurrencies(); ?>
    <?php $currentCurrencyCode = $block->getCurrentCurrencyCode(); ?>
    <?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : '' ?>
    <div class="switcher currency switcher-currency" id="switcher-currency<?= $block->escapeHtmlAttr($id) ?>">
        <strong class="label switcher-label"><span><?= $block->escapeHtml(__('Currency')) ?></span></strong>
        <div class="actions dropdown options switcher-options">
            <div class="action toggle switcher-trigger"
                 id="switcher-currency-trigger<?= $block->escapeHtmlAttr($id) ?>"
                 data-mage-init='{"dropdown":{}}'
                 data-toggle="dropdown"
                 data-trigger-keypress-button="true">
                <strong class="language-<?= $block->escapeHtml($block->getCurrentCurrencyCode()) ?>">
                    <span><?= $block->escapeHtml($currentCurrencyCode) ?><span> (<?= $currencySymbol ?>)</span></span>
                </strong>
            </div>
            <ul class="dropdown switcher-dropdown" data-target="dropdown">
                <?php foreach ($currencies as $_code => $_name): ?>
                    <?php if ($_code == $currentCurrencyCode){ ?>
                        <li class="currency-<?= $block->escapeHtmlAttr($_code) ?> switcher-option">
                            <span><?= $block->escapeHtml($_code) ?></span>
                        </li>
                    <?php } else { ?>
                        <li class="currency-<?= $block->escapeHtmlAttr($_code) ?> switcher-option">
                            <a href="#" data-post='<?= /* @noEscape */ $block->getSwitchCurrencyPostData($_code) ?>'><?= $block->escapeHtml($_code) ?><span style="display: none"> - <?= $block->escapeHtml($_name) ?></span></a>
                        </li>
                    <?php } ?>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
<?php endif; ?>
