<?php 
/**
* @Author      : Kien
* @package     Marketplace
* @copyright   Copyright (c) 2016 MAGEBAY (http://www.magebay.com)
* @terms  http://www.magebay.com/terms
* @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
**/
?>
<div class="page-head-actions" style="margin-bottom: 10px;" >
    <div class="row">
        <div class="col-sm-6"></div>
        <div class="col-sm-6">
            <div class="actions-buttons" >
                <div class="btn-group mv-btn-group prod-button">
                    <button type="button" class="btn btn-primary btn-red btn-add-products redirect_add_product" redirect="<?php echo $this->getUrl('marketplace/product/create',array('set'=>'4','type'=>'simple')) ?>"><?php echo __('Add Product') ?></button>
                    <button type="button" class="btn btn-primary dropdown-toggle btn-red" data-toggle="dropdown">
                        <span class="caret"></span>
                    </button>				  
                    <ul class="dropdown-menu" data-ui-id="save-button-dropdown-menu">
                        <li><a href="#" ><span id="save_and_draft" class="item redirect_add_product" redirect="<?php echo $this->getUrl('marketplace/product/create',array('set'=>'4','type'=>'simple')) ?>" data-ui-id="save-button-item-0"><?php echo __('Simple Product') ?></span></a></li>
                        <li><a href="#" ><span id="save_and_new" class="item redirect_add_product" redirect="<?php echo $this->getUrl('marketplace/product/create',array('set'=>'4','type'=>'downloadable')) ?>" data-ui-id="save-button-item-1"><?php echo __('Downloadable Product') ?></span></a></li>
                        <li><a href="#" ><span id="save_and_duplicate" class="item redirect_add_product" redirect="<?php echo $this->getUrl('marketplace/product/create',array('set'=>'4','type'=>'virtual')) ?>" data-ui-id="save-button-item-2"><?php echo __('Virtual Product') ?></span></a></li>
                        <li><a href="#" ><span id="save_and_close" class="item redirect_add_product" redirect="<?php echo $this->getUrl('marketplace/product/create',array('set'=>'4','type'=>'configurable')) ?>" data-ui-id="save-button-item-3"><?php echo __('Configurable Product') ?></span></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    require([
        "jquery",
    ], function($){
        $('.redirect_add_product').click(function(event){
            window.location = $(this).attr('redirect');
            event.preventDefault();
        });
        $( ".actions-buttons .dropdown-toggle" ).click(function() {
            $( ".actions-buttons .dropdown-menu" ).toggle();
		});
    });
</script>
<style>
    .btn-add-products{
        padding: 7px 33px;
    }
    .page-head-actions {
        background: #f8f8f8 none repeat scroll 0 0;
        border: 1px solid #e3e3e3;
        padding: 10px 15px;
    }
    .page-head-actions .actions-buttons {
        text-align: right;
    }
    .btn-group.prod-button {
        display: inline-block !important;
    }
    .btn-group, .btn-group-vertical {
        display: inline-block;
        position: relative;
        vertical-align: middle;
    }
    .btn-group > .btn + .dropdown-toggle {
        padding-left: 8px;
        padding-right: 8px;
    }
    .btn-group .btn + .btn, .btn-group .btn + .btn-group, .btn-group .btn-group + .btn, .btn-group .btn-group + .btn-group {
        margin-left: -1px;
    }
    .btn-group > .btn-group:last-child:not(:first-child) > .btn:first-child, .btn-group > .btn:last-child:not(:first-child), .btn-group > .dropdown-toggle:not(:first-child) {
        border-bottom-left-radius: 0;
        border-top-left-radius: 0;
    }
    .btn-group-vertical > .btn, .btn-group > .btn {
        float: left;
        position: relative;
    }
    .btn.btn-red {
        background-color: #eb5202;
        border-color: #b25524;
        color: #fff;
    }
    button:not(.primary) {
        box-shadow: 0 1px 0 0 #fff inset, 0 -1px 0 0 rgba(204, 204, 204, 0.3) inset;
    }
    .btn .caret, .btn-group > .btn:first-child {
        margin-left: 0;
    }
    .caret {
        border-left: 4px solid transparent;
        border-right: 4px solid transparent;
        border-top: 4px dashed;
        display: inline-block;
        height: 0;
        margin-left: 2px;
        vertical-align: middle;
        width: 0;
    }
    .btn-group.prod-button .dropdown-menu::before, .btn-group.prod-button .dropdown-menu::after {
        border: medium none !important;
    }
    .btn-group > .dropdown-menu::before, .dropdown-toggle > .dropdown-menu::before, .dropdown > .dropdown-menu::before {
        border-bottom: 8px solid #e0e0e0;
        border-left: 8px solid transparent;
        border-right: 8px solid transparent;
        content: "";
        display: inline-block !important;
        left: 9px;
        position: absolute;
        right: auto;
        top: -8px;
    }
    *, *::after, *::before {
        box-sizing: border-box;
    }
    .btn-group.prod-button .dropdown-menu::before, .btn-group.prod-button .dropdown-menu::after {
        border: medium none !important;
    }
    .btn-group > .dropdown-menu::after, .dropdown-toggle > .dropdown-menu::after, .dropdown > .dropdown-menu::after {
        border-bottom: 7px solid #fff;
        border-left: 7px solid transparent;
        border-right: 7px solid transparent;
        content: "";
        display: inline-block !important;
        left: 10px;
        position: absolute;
        right: auto;
        top: -7px;
    }
    .btn-group.prod-button .dropdown-menu {
        box-shadow: 2px 2px rgba(102, 102, 102, 0.1);
        margin: 2px 0 0;
        min-width: 140px;
    }
    .btn-group > .dropdown-menu, .dropdown-toggle > .dropdown-menu, .dropdown > .dropdown-menu {
        margin-top: 10px;
    }
    .dropdown-menu {
        background-clip: padding-box;
        background-color: #fff;
        border: 1px solid rgba(0, 0, 0, 0.15);
        border-radius: 4px;
        box-shadow: 0 6px 12px rgba(0, 0, 0, 0.176);
        display: none;
        font-size: 14px;
        left: 0;
        list-style: outside none none;
        margin: 2px 0 0;
        min-width: 160px;
        padding: 5px 0;
        position: absolute;
        text-align: left;
        top: 100%;
        z-index: 1000;
    }
    .btn-group > .btn-group, .btn-toolbar .btn, .btn-toolbar .btn-group, .btn-toolbar .input-group, .col-xs-1, .col-xs-10, .col-xs-11, .col-xs-12, .col-xs-2, .col-xs-3, .col-xs-4, .col-xs-5, .col-xs-6, .col-xs-7, .col-xs-8, .col-xs-9, .dropdown-menu {
        float: left;
    }
    a, button, code, div, img, input, label, li, p, pre, select, span, svg, table, td, textarea, th, ul {
        border-radius: 0 !important;
    }
    .dropdown-menu > li > a {
        clear: both;
        color: #6f6f6f;
        display: block;
        font-weight: 300;
        line-height: 18px;
        padding: 8px 16px;
        text-decoration: none;
        white-space: nowrap;
    }
    .dropdown-menu > li > a:focus, .dropdown-menu > li > a:hover {
        color: #262626;
        background-color: #e3e3e3;
    }
</style>