<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var \Magento\Wishlist\Block\Customer\Wishlist\Item\Options $block */
?>

<?php $options = $block->getOptionList(); ?>
<?php if ($options): ?>
<div class="tooltip wrapper product-item-tooltip">
  <span class="action details tooltip toggle"><?= $block->escapeHtml(__('See Details')) ?></span>
  <div class="tooltip content">
      <strong class="subtitle"><?= $block->escapeHtml(__('Options Details')) ?></strong>
      <dl>
          <?php foreach ($options as $option): ?>
              <?php if( $option['label'] != __('Check Out') ){ ?>
                  <dt class="label"><?= $block->escapeHtml($option['label']) ?></dt>
                  <dd class="values">
                      <?php if (is_array($option['value'])): ?>
                      <?= /* @noEscape */ nl2br(implode("\n", $option['value'])) ?>
                      <?php else: ?>
                      <?= /* @noEscape */ $option['value'] ?>
                      <?php endif; ?>
                  </dd>
              <?php } ?>
          <?php endforeach; ?>
      </dl>
  </div>
</div>
<?php endif ?>
<div class="clear clearfix"></div>
