<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var $block \Magento\Theme\Block\Html\Title
 */
$_productCollection = $block->getLayout()->getBlock('search_result_list')->getLoadedProductCollection();
$count = $_productCollection->getSize();
$cssClass = $block->getCssClass() ? ' ' . $block->getCssClass() : '';
$title = '';
if (trim($block->getPageHeading())) {
    $title = '<span class="base" data-ui-id="page-title-wrapper" ' .  $block->getAddBaseAttribute() . '>'
        . "<strong>" . $count . "</strong> " . 
        "Search ".$block->escapeHtml($block->getPageHeading()) 
        . '</span>';
}
?>
<?php if ($title): ?>

    <?php if($count): ?>
    <div class="page-title-wrapper<?= /* @escapeNotVerified */ $cssClass ?>">
        <h1 class="page-title"
            <?php if ($block->getId()): ?> id="<?= /* @escapeNotVerified */ $block->getId() ?>" <?php endif; ?>
            <?php if ($block->getAddBaseAttributeAria()): ?>
                aria-labelledby="<?= /* @escapeNotVerified */ $block->getAddBaseAttributeAria() ?>"
            <?php endif; ?>>
            <?= /* @escapeNotVerified */ $title ?>
        </h1>
        <?= $block->getChildHtml() ?>
    </div>
        <script type="text/javascript">
            fbq('track', 'Search');
        </script>

    <?php else: ?>

    <div class="page-title-wrapper no-result">
        <div class="inner-title">
            <img src="<?= $block->getViewFileUrl('images/no-results.png'); ?>">
            <h1 class="page-title"
                <?php if ($block->getId()): ?> id="<?= /* @escapeNotVerified */ $block->getId() ?>" <?php endif; ?>
                <?php if ($block->getAddBaseAttributeAria()): ?>
                    aria-labelledby="<?= /* @escapeNotVerified */ $block->getAddBaseAttributeAria() ?>"
                <?php endif; ?>>
                <?= "Oops! No Search ".$block->escapeHtml($block->getPageHeading()) ?>
            </h1>
            <p><?= __('Feel lost? Please') ?> <a href="<?= $this->getUrl('contact-us') ?>"><?= __('Contact us') ?></a></p>
        </div>
    </div>
    <?php endif; ?>
<?php endif; ?>
