<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\CatalogWidget\Block\Product\ProductsList $block */
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())): ?>
    <?php
    $type = 'widget-new-grid';

    $image = 'category_page_grid';
    $items = $block->getProductCollection()->getItems();

    $itemsToShow = $block->getData('products_count_slider');

    $showWishlist = true;
    $showCompare = false;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $description = false;
    ?>

            <div class="product-list-carousel-vertical" >

                <a href="#" class="vc_goUp"><i class="fa fa-fw fa-angle-up"></i></a>
                <ul class="vc_list list-product <?php if(count($items) > 1): ?>product-slide <?php else: ?>one-product<?php endif; ?>">
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $_item): ?>
                    <?php if ($iterator++ != 1): ?></li><?php endif; ?>
                    <li class="product-item">
                        <div class="product-item-info">
                            <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>" class="product-item-photo">
                                <div style="background-image: url(<?= $block->getImage($_item, $image)->getImageUrl(); ?>)"></div>
                            </a>
                            <div class="product-item-details">
                                <strong class="product-item-name">
                                    <a title="<?= $block->escapeHtml($_item->getName()) ?>"
                                       href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                       class="product-item-link">
                                        <?= $block->escapeHtml($_item->getName()) ?>
                                    </a>

                                    <?php if ($templateType): ?>
                                        <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                    <?php endif; ?>
                                </strong>
                                <div class="info-product-bottom">
                                    <div class="block-price">
                                        <span class="label-price">from</span>
                                        <?php echo $block->getProductPriceHtml($_item, $type); ?>
                                    </div>
                                    <?php if ($showWishlist || $showCart): ?>
                                        <div class="product-item-actions">
                                            <?php if ($showCart): ?>
                                                <div class="actions-primary">
                                                    <?php if ($_item->isSaleable()): ?>
                                                        <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                            <a  href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"  class="action tocart primary">
                                                                <span><?= $block->escapeHtml(__('Book Now')) ?></span>
                                                            </a>
                                                        <?php else: ?>
                                                            <?php
                                                            $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                            $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                            ?>
                                                            <a  href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"  class="action tocart primary">
                                                                <span><?= $block->escapeHtml(__('Book Now')) ?></span>
                                                            </a>
                                                        <?php endif; ?>
                                                    <?php else: ?>
                                                        <?php if ($_item->getIsSalable()): ?>
                                                            <div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
                                                        <?php else: ?>
                                                            <div class="stock unavailable"><span><?= $block->escapeHtml(__('Out of stock')) ?></span></div>
                                                        <?php endif; ?>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endif; ?>
                                            <?php if ($showWishlist): ?>
                                                <div class="actions-secondary add-wishlist" data-role="add-to-links">
                                                    <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                                        <a href="#"
                                                           data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($_item) ?>' class="action towishlist" data-action="add-to-wishlist" title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>">
                                                            <span class="icon-wishlist"></span>
                                                        </a>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                        <?= ($iterator == count($items)+1) ? '</li>' : '' ?>
                        <?php endforeach ?>
                </ul>
                <a href="#" class="vc_goDown"><i class="fa fa-fw fa-angle-down"></i></a>
            </div>

    <script>
        require(
            [
                'jquery',
                'js/jQuery.verticalCarousel'
            ],function($,slider){

                $(".product-list-carousel-vertical").verticalCarousel({
                    currentItem: 1,
                    showItems: <?= $itemsToShow ?>,
                });
            })
    </script>

<?php endif;?>
