<?php

$_gridPopupBlock = $block->getChildBlock('marketplace_product_group_grid_popup_container')->getChildBlock('grid');
$_gridPopupBlock->setRowClickCallback('function(){}');
?>
<div id="grouped-product-container" data-mage-init='{"groupedProduct":{"gridPopup":"[data-grid-id=<?php /* @escapeNotVerified */ echo $_gridPopupBlock->getId() ?>]"}}'>
    <div class="no-products-message">
        <?php /* @escapeNotVerified */ echo __('There are no grouped products.')?>
    </div>
    <?php echo $block->getChildHtml('list'); ?>
    <div data-role="add-product-dialog" class="no-display">
        <?php echo $block->getChildBlock('marketplace_product_group_grid_popup_container')->getChildHtml('grid');?>
    </div>
	<div class="block-group-button" style="margin:5px 0;">
		<button type="button" data-role="add-product"><?php echo __('Add Products to Group') ?></button>
	</div>
</div>
