
<?php
/**
 * @var $block \Magebay\Bookingsystem\Block\Booking
 */
?>
<?php $booking = $block->getBkBookingItem(); ?>
<?php $request = $block->getBookingRequest(); ?>
<?php $maxBooking = $this->getBkHelperDate()->getFieldSetting('bookingsystem/setting/max_booking') ?>
<?php $typeTime = $block->getBkHelperDate()->getFieldSetting('bookingsystem/setting/time_mode'); ?>
<?php $addonsSelles = $block->getAddonsSelles(); ?>
<?php $bkIntCurrentTime = $block->getBkTmpTime(); ?>
<?php $bkCheckInCheckOut = $request['check_in'] != '' ? $request['check_in'] . ' - ' .$request['check_out'] : '' ?>
<div class="simple-booking-form booking-form">
    <input id="booking-time-type" type="hidden" name="booking_time_type" value="per_day" />
    <input type="hidden" name="bk_item_id" value="<?php echo $request['item_id']; ?>"  />
    <div class="simple-booking-form-input">
        <div class="row-6 mt-sm">
            <div class="col-sm-12 col-xs-12 date-box date-box-checkin">
                <div class="input-date">
                    <label><?php echo __('Check In'); ?></label>
                    <div class="form-group" >
                        <div class="select-date" >
                            <i id="check-in-button" class="fa fa-calendar input-icon"></i>
                            <input type="text"  id="bk-checkin-checkout" name="bk_checkin_checkout" value="<?php echo ($request['check_in'] != '' && $request['check_out'] != '') ? $request['check_in'] . ' - ' .$request['check_out'] : ''; ?>" class="form-control" onfocus="blur();">
                            <input type="hidden" class="form-control input-text" name="check_in" id="check-in" value="<?php echo $request['check_in']; ?>">
                            <input type="hidden" class="form-control input-text" name="check_out" id="check-out" value="<?php echo $request['check_out']; ?>">
                        </div>
                    </div>
                </div>

            </div>
        </div>
        <!-- Addons & Cross-sells -->
        <?php if(count($addonsSelles)) : ?>
            <div class="addons-cross-sells">
                <dl>
                    <?php foreach($addonsSelles as $addonsSelle) : ?>
                        <?php $requestAddon =  isset($request['addons'][$addonsSelle->getId()]) ? $request['addons'][$addonsSelle->getId()] : ''; ?>
                        <?php $addonRadioCheckoxClass = ''; ?>
                        <?php if($addonsSelle->getOptionType() == 4 || $addonsSelle->getOptionType() == 5) :  ?>
                            <?php $addonRadioCheckoxClass = 'bk-addon-radio-checkbox';  ?>
                            <?php if($addonsSelle->getOptionRequired() == 1) { $addonRadioCheckoxClass .= ' required-empty'; } ?>
                        <?php endif; ?>
                        <dt>
                            <label for="addon-<?php echo $addonsSelle->getId(); ?>" <?php if ($addonsSelle->getOptionRequired() == 1) { echo 'class="required"'; } ?> >
                                <?php if ( $addonsSelle->getOptionRequired() == 1) { echo '<em>*</em>'; } ?>
                                <?php $title = $block->getBkHelperText()->showTranslateText($addonsSelle->getOptionTitle(),$addonsSelle->getOptionTitleTranslate()); ?>
                                <?php echo $title; ?>
                                <?php
                                if ( $addonsSelle->getOptionPrice() > 0 ) {
                                    echo  '<span class="price-notice"> +<span class="price">'.$block->getBkPriceHelper()->currency($addonsSelle->getOptionPrice(), true, false).'</span></span>';
                                }
                                ?>
                            </label>
                        </dt>
                        <dd <?php if($addonRadioCheckoxClass != '') { ?>class="<?php echo $addonRadioCheckoxClass; ?>" id="bk-addon-radio-checkbox-<?php echo $addonsSelle->getId(); ?>"<?php } ?>>
                            <div class="addons-sells-item input-box">
                                <?php if($addonsSelle->getOptionType() == 2) : ?>
                                    <select class="select-addons-item<?php if($addonsSelle->getOptionRequired() == 1) echo ' required-empty'; ?>" name="addons[<?php echo $addonsSelle['option_id'] ?>]">
                                        <option value=""><?php echo __('Select Options'); ?></option>
                                        <?php $selectValues = $block->getBkOptionSelectValues($addonsSelle->getId()); ?>
                                        <?php if(count($selectValues)) : ?>
                                            <?php foreach($selectValues as $selectValue) : ?>
                                                <option value="<?php echo $selectValue->getId(); ?>" <?php if($requestAddon == $selectValue->getId()) { echo 'selected="selected"'; } ?>>
                                                    <?php $valueTitle = $block->getBkHelperText()->showTranslateText($selectValue->getDropdownTitle(),$selectValue->getDropdownTitleTranslate()); ?>
                                                    <?php echo $valueTitle; ?>
                                                    <?php
                                                    if ( $selectValue->getDropdownPrice() > 0 ) { echo ' +'.$block->getBkPriceHelper()->currency( $selectValue->getDropdownPrice(), true, false); }
                                                    ?>
                                                </option>
                                            <?php endforeach; ?>
                                        <?php endif; ?>
                                    </select>
                                <?php elseif($addonsSelle->getOptionType() == 3) : ?>
                                    <select multiple class="select-addons-item<?php if($addonsSelle->getOptionRequired() == 1) echo ' required-empty'; ?>" name="addons[<?php echo $addonsSelle['option_id'] ?>][]">
                                        <?php $selectValues = $block->getBkOptionSelectValues($addonsSelle->getId()); ?>
                                        <?php if(count($selectValues)) : ?>
                                            <?php foreach($selectValues as $selectValue) : ?>
                                                <option value="<?php echo $selectValue->getId(); ?>" <?php if(is_array($requestAddon) && count($requestAddon) && in_array($selectValue->getId(),$requestAddon)) { echo 'selected="selected"'; } ?>>
                                                    <?php $valueTitle = $block->getBkHelperText()->showTranslateText($selectValue->getDropdownTitle(),$selectValue->getDropdownTitleTranslate()); ?>
                                                    <?php echo $valueTitle; ?>
                                                    <?php
                                                    if ( $selectValue->getDropdownPrice() > 0 ) { echo ' +'.$block->getBkPriceHelper()->currency( $selectValue->getDropdownPrice(), true, false); }
                                                    ?>
                                                </option>
                                            <?php endforeach; ?>
                                        <?php endif; ?>
                                    </select>
                                <?php elseif($addonsSelle->getOptionType() == 4) : ?>
                                    <?php $readioValues = $block->getBkOptionSelectValues($addonsSelle->getId()); ?>
                                    <?php if(count($readioValues)) : ?>
                                        <?php foreach($readioValues as $readioValue) : ?>
                                            <div class="addons-input-item">
                                                <input type="radio" name="addons[<?php echo $addonsSelle['option_id'] ?>]" value="<?php echo $readioValue->getId(); ?>"  <?php if($requestAddon == $readioValue->getId()) { echo 'checked="checked"'; } ?>  />
                                                <?php $valueTitle = $block->getBkHelperText()->showTranslateText($readioValue->getDropdownTitle(),$readioValue->getDropdownTitleTranslate()); ?>
                                                <span class="bk-addon-title"><?php echo $valueTitle; ?>
                                                    <?php
                                                    if ( $selectValue->getDropdownPrice() > 0 ) { echo ' +'.$block->getBkPriceHelper()->currency( $readioValue->getDropdownPrice(), true, false); }
                                                    ?>
										</span>
                                            </div>
                                        <?php endforeach; ?>
                                    <?php endif; ?>
                                <?php elseif($addonsSelle->getOptionType() == 5) : ?>
                                    <?php $checkboxValues = $block->getBkOptionSelectValues($addonsSelle->getId()); ?>
                                    <?php if(count($checkboxValues)) : ?>
                                        <?php foreach($checkboxValues as $checkboxValue) : ?>
                                            <div class="addons-input-item">
                                                <input type="checkbox" name="addons[<?php echo $addonsSelle['option_id'] ?>][]" value="<?php echo $checkboxValue->getId(); ?>"  <?php if(is_array($requestAddon) && count($requestAddon) && in_array($checkboxValue->getId(),$requestAddon)) { echo 'checked="checked"'; } ?>  />
                                                <?php $valueTitle = $block->getBkHelperText()->showTranslateText($checkboxValue->getDropdownTitle(),$checkboxValue->getDropdownTitleTranslate()); ?>
                                                <span class="bk-addon-title"><?php echo $valueTitle; ?>
                                                    <?php
                                                    if ( $checkboxValue->getDropdownPrice() > 0 ) { echo ' +'.$block->getBkPriceHelper()->currency( $checkboxValue->getDropdownPrice(), true, false); }
                                                    ?>
										</span>
                                            </div>
                                        <?php endforeach; ?>
                                    <?php endif; ?>
                                <?php else : ?>
                                    <input class="txt-addons-item input-text <?php if($addonsSelle->getOptionRequired() == 1) echo 'required-empty'; ?>" type="text" name="addons[<?php echo $addonsSelle->getId(); ?>]" value="<?php echo $requestAddon; ?>" />
                                <?php endif; ?>
                            </div>
                        </dd>
                    <?php endforeach; ?>
                </dl>
            </div>
        <?php endif; ?>
        <!--end Addons & Cross-sells-->
        <!-- hidden input -->
        <input type="hidden" id="temp-check-in" name="temp_check_in" value="<?php echo $request['temp_check_in']; ?>" />
        <input type="hidden" id="temp-check-out" name="temp_check_out" value="<?php echo $request['temp_check_out']; ?>" />
        <input type="hidden" id="temp-check-load" name="temp_check_load" value="0" />
    </div>
    <div class="booking-book">
        <div class="booking-quantity booking-quantity-tours">
            <div style="display: none">
                <span><?php echo __('Qty'); ?></span>
                <select name="qty" id="booking-qty">
                    <option value="1">1</option>
                </select>
            </div>
            <div class="bk-extract-price-person">

            </div>
        </div>
        <!--default price-->
        <input type="hidden" name="magebay_base_product_price" id="magebay-base-product-price" value="0" />
        <input type="hidden" name="bookingsystem_total_price" id="bookingsystem-total-price" value="0" />
        <div class="booking-results">

        </div>
        <div class="booking-message-discount">
            <?php $textDayHours = __('Persons'); ?>
            <?php $discounts = $block->getBkDiscounts(); ?>
            <?php if(count($discounts)) : ?>
                <span class="discount-label"><b><?php echo __('Available discount for checkout:'); ?></b></span>
                <?php foreach($discounts as $discount) : ?>
                    <?php if($discount['discount_type'] == '1') : ?>
                        <span class="last-minute"><?php echo __('For reservations statring until %1 you get a %2 discount ',$discount['date_condition'],$discount['type_amount_text']); ?> <?php if($discount['discount_max_items'] > 0)  { echo __('for a maximum of %1 %2',$discount['discount_max_items'],$textDayHours); } ?></span>
                    <?php elseif($discount['discount_type'] == '2') : ?>
                        <span class="first-moment"><?php echo __('For reservations stating after %1 you get a %2 discount ',$discount['date_condition'],$discount['type_amount_text']); ?> <?php if($discount['discount_max_items'] > 0)  { echo __('for a maximum of %1 %2',$discount['discount_max_items'],$textDayHours); } ?></span>
                    <?php else : ?>
                        <span class="length-reservations"><?php echo __('For reservations of more than %1 %2 you get a %3 discount ',$discount['discount_period'],$textDayHours,$discount['type_amount_text']); ?> <?php if($discount['discount_max_items'] > 0) { echo __('for a maximum of %1 %2',$discount['discount_max_items'],$textDayHours); } ?></span>
                    <?php endif; ?>
                <?php endforeach; ?>
            <?php endif; ?>
        </div>
        <?php
        if($request['action'] == 'configure')
        {
            echo $this->getLayout()->createBlock('Magento\Catalog\Block\Product\View')->setTemplate('Magebay_Bookingsystem::product/view/configure/updatecart.phtml')->toHtml();
        }
        else
        {
            echo $this->getLayout()->createBlock('Magento\Catalog\Block\Product\View')->setTemplate('Magebay_Bookingsystem::product/view/addtocart.phtml')->toHtml();
        }
        ?>
    </div>
</div>

