<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Newsletter\Block\Subscribe $block */

?>
<div class="block newsletter">
    <div class="block-title"><strong><span><?= $block->escapeHtml(__('Suscribe Daytours4u')) ?></span></strong></div>
    <div class="content">
        <form class="form subscribe"
              novalidate
              action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>"
              method="post"
              data-mage-init='{"validation": {"errorClass": "mage-error"}}'
              id="newsletter-validate-detail">
            <div class="field newsletter">
                <label class="label" for="newsletter"><span><?= $block->escapeHtml(__('Receive our emails and be the first to know about exclusive offers, promotions, and interesting travel posts.')) ?></span></label>
                <div class="control">
                    <input name="email" type="email" id="newsletter"
                           placeholder="<?= $block->escapeHtmlAttr(__('Your email...')) ?>"
                           data-validate="{required:true, 'validate-email':true}"/>

                    <div class="actions">
                        <button class="action subscribe primary" title="<?= $block->escapeHtmlAttr(__('Subscribe')) ?>" type="submit">
                            <span><?= $block->escapeHtml(__('Subscribe')) ?></span>
                        </button>
                    </div>
                </div>
            </div>

        </form>
    </div>
</div>
