<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Newsletter\Block\Subscribe $block */

?>

<form class="form subscribe-ajax"
      novalidate
      action="<?= $block->getUrl('newsletterajax/create/newsubscribe') ?>"
      method="post"
      data-mage-init='{"validation": {"errorClass": "mage-error"}}'
      id="newsletter-validate-detail-ajax">
    <div class="field newsletter">
        <div class="control">

            <div class="error-newsletter-ajax message error"></div>
            <div class="success-newsletter-ajax message success"></div>

            <input name="emailNewsleter" type="email" id="email-newsletter-ajax" class="input-text-nll"
                   placeholder="<?= $block->escapeHtmlAttr(__('Email*')) ?>"
                   data-validate="{required:true, 'validate-email':true}"/>
            <input type="hidden" name="format" id="format" value="json">

            <div class="content-button">
                <button id="subscribe-ajax" class="action subscribe primary" title="<?= $block->escapeHtmlAttr(__('I want my code')) ?>" type="submit">
                    <span><?= $block->escapeHtml(__('I want my code')) ?></span>
                </button>
            </div>
        </div>
    </div>
</form>

<script type="text/x-magento-init">
    {
        "*": {
            "Daytours_Newsletter/js/newsletter-ajax" : {
                "ajaxUrl" : "<?= $block->getUrl('newsletterajax/create/newsubscribe') ?>"
            }
        }
    }
</script>