<?php

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();

/** @var  \Daytours\EditOrder\Helper\Data $helperEditOrder */

$helperEditOrder = $this->helper("Daytours\EditOrder\Helper\Data");

$viewModel = $block->getViewModel();
$orderId = $this->getOrderId();
$_order = $viewModel->getOrderById($this->getOrderId());

//$_order = $this->getOrder();
$order_increment_id = $_order->getIncrementId();

$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$store = $storeManager->getStore();

?>

<?php if($helperEditOrder->isVisibleCompleteOrderButton($order_increment_id)) : ?>

<tr class="email-complete phtml-file" style="padding: 0 25px;margin-bottom: 40px;margin-top: 40px;display: block">
    <td>
        <div class="complete_order_wrapper">
            <h3><?= __('We need you to complete one more step') ?></h3>
            <p><?= __('Click the link below and make sure you will enter all the requested details. These details are necessary to confirm your booking and send you the voucher.') ?></p>
            <a href="<?php echo $helperEditOrder->getURLEncrypted($_order->getEntityId(),$_order->getCustomerEmail(),$_order->getStoreId())  ?>" class="btn-complete-order"><?= __('Complete Order') ?></a>
        </div>
    </td>
</tr>
<?php endif; ?>