<?php
/**
 * @Author      : haunv
 * @package     Marketplace
 * @copyright   Copyright (c) 2017 MAGEBAY (http://www.magebay.com)
 * @terms  http://www.magebay.com/terms
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 **/
$helper=$this->helper('Magebay\Marketplace\Helper\Data');
$currencySymbol=$helper->getCurrencySymbol();
$taxcollection=$helper->getTaxConnection();
$visibility=$block->getOptionVisibility();
$group=$block->getOptionSetGroup();
$_productDetail=$block->getProduct();
$_helper=$this->helper('Magento\Catalog\Helper\Output');
$_hasweight=$_productDetail->getTypeInstance()->hasWeight();
$_quanlityArray=$block->getQtyProduct($_productDetail->getId(),$_productDetail->getStore()->getWebsiteId());
$_quanlity=(int)$_quanlityArray[$_productDetail->getId()];
$stockStatus=$block->getStockStatus($_productDetail->getId(),$_productDetail->getStore()->getWebsiteId());
$attributeSetid=$_productDetail->getAttributeSetId();
if($set=$block->getParamSet()){
	$attributeSetid=$set;
}
$typeId = '';
$bkId = $this->getRequest()->getParam('id',0);
$bkId = (int)$bkId;
if($bkId == 0)
{
    $typeId = $this->getRequest()->getParam('type','');
}
else
{
    $typeId = $_productDetail->getTypeId();
}
?>
<div class="block block-formadd-newproduct">
	<div class="block block-content">
		<form method="post" action="<?php echo $block->getActionForm() ?>" class="form form-addnew-product" data-form="edit-product" id="form-seller-add-newproduct" enctype="multipart/form-data" >
			<input type="hidden" id="type_save" class="type_save" name="back"/>
            <?php echo $block->getBlockHtml('formkey')?>
			<fieldset id="associate-product" class="fieldset info">
                <?php if($this->getRequest()->getParam('id')){ ?>
				    <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Edit Product') ?></span></legend>
                <?php }else{ ?>
                    <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Add Product') ?></span></legend>
                <?php } ?>
                <div class="page-head-actions" >
                    <div class="row">
                        <div class="col-sm-6"></div>
                        <div class="col-sm-6">
                            <div class="actions-buttons" >
                                <!--<button title="<?php echo __('Save') ?>" type="submit" class="btn btn-default btn-success" role="button"><span><span><?php echo __('Save') ?></span></span></button>-->
                                <div class="btn-group mv-btn-group prod-button">
                                    <button type="button" class="btn btn-primary btn-red save_product" redirect="submit" data-ui-id="save-button-item-default"><?php echo __('Save Product') ?></button>
                                    <button type="button" class="btn btn-primary dropdown-toggle btn-red" data-toggle="dropdown">
                                        <span class="caret"></span>
                                    </button>				  
                                    <ul class="dropdown-menu" data-ui-id="save-button-dropdown-menu">
                                        <li><a href="#" ><span id="save_and_draft" class="item save_product" redirect="draft" data-ui-id="save-button-item-0"><?php echo __('Save & Draft') ?></span></a></li>
                                        <li><a href="#" ><span id="save_and_new" class="item save_product" redirect="new" data-ui-id="save-button-item-1"><?php echo __('Save & New') ?></span></a></li>
                                        <li><a href="#" ><span id="save_and_duplicate" class="item save_product" redirect="duplicate" data-ui-id="save-button-item-2"><?php echo __('Save & Duplicate') ?></span></a></li>
                                        <li><a href="#" ><span id="save_and_close" class="item save_product" redirect="close" data-ui-id="save-button-item-3"><?php echo __('Save & Close') ?></span></a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <br />
				<input type="hidden" id="product_type_id" value="<?php /* @escapeNotVerified */ echo $block->getProductTypeId() ?>" />
				<div class="fieldset form-list">
					<div class="field group required">
						<label class="label"><span><?php echo __('Attribute Set: ') ?></span></label>
						<div class="control">
							<?php if(count($group)){ ?>
								<select name="set" class="required-entry">
    								<?php foreach($group as $k=>$v) {?>	
                                        <?php if(($v['value'] == $this->getRequest()->getParam('set')) || ($attributeSetid==$v['value'])){ ?>								
    									   <option value="<?php echo $v['value']?>" <?php echo $attributeSetid==$v['value']?'selected':'' ?>><?php echo $v['label']?></option>
    								    <?php } ?>
                                    <?php } ?>
								</select>
							<?php } ?>
						</div>
					</div>
					<div class="field categorycollection">
						<?php echo $block->getChildHtml('categoriecollection') ?>
					</div>
					<div class="field required">
						<label class="label" ><span><?php echo __('Product Name : ') ?></span></label>
						<div class="control">
							<input type="text" title="<?php echo $block->stripTags($_productDetail->getName(), null, true) ?>" value="<?php echo $_helper->productAttribute($_productDetail, $_productDetail->getName(), 'name') ?>" class="validate-length maximum-length-255 required-entry input-text required-entry _required" name="product[name]" aria-required="true" />
						</div>
					</div>
                    <style>                    
    					#mb-ajaxloading {
                            display: none;
                            float: right;
                            margin: 0 10px;
                            top: 1px;
                            position: unset;
                        }
                    </style>                        
					<div class="field required">
						<label class="label" >
                            <span><?php echo __('Sku : ') ?></span>
                            <div id="mb-ajaxloading">
                                <img width="20px" height="20px" src="<?php echo $block->getViewFileUrl('images/loader-1.gif') ?>">
                            </div>
                        </label>
						<div class="control">
							<input type="text" value="<?php echo $_helper->productAttribute($_productDetail, $_productDetail->getSku(), 'sku') ?>" class="validate-length maximum-length-64 required-entry input-text required-entry _required" id="sku" name="product[sku]" aria-required="true" />
						</div>
					</div>
                    <div class="messages" >
                        <div class="message-notice notice message sku_false" data-ui-id="message-notice" style="display: none;">
                            <div>This SKU is not available.</div>
                        </div>
                        <div class="message-success success message sku_true" data-ui-id="message-success" style="display: none;">
                            <div>This SKU is available.</div>
                        </div>
                    </div>
					<div class="field required">
						<label class="label" ><span><?php echo __('Description : ') ?></span></label>
						<div class="control">
							<textarea data-ui-id="product-tabs-attributes-tab-fieldset-element-textarea-product-description" cols="15" rows="2" class="textarea" name="product[description]" id="description"><?php echo $_helper->productAttribute($_productDetail, $_productDetail->getDescription(), 'description') ?></textarea>
							<script>
								require([
									'jquery',
									'mage/adminhtml/wysiwyg/tiny_mce/setup'
								], function(jQuery){

									var config = '<?php echo $block->getWysiwygConfig() ?>',
										editor;

									jQuery.extend(config, {
										settings: {
											theme_advanced_buttons1 : 'bold,italic,|,justifyleft,justifycenter,justifyright,|,' +
												'fontselect,fontsizeselect,|,forecolor,backcolor,|,link,unlink,image,|,bullist,numlist,|,code',
											theme_advanced_buttons2: null,
											theme_advanced_buttons3: null,
											theme_advanced_buttons4: null,
											theme_advanced_statusbar_location: null
										},
										files_browser_window_url: false
									});

									editor = new tinyMceWysiwygSetup(
										'description',
										config
									);
									editor.turnOn();

									jQuery('#description')
									.addClass('wysiwyg-editor')
									.data(
										'wysiwygEditor',
										editor
									);
								});
							</script>							
						</div>
					</div>
					<div class="field required">
						<label class="label" ><span><?php echo __('Price('.$currencySymbol.'): ') ?></span></label>
						<div class="control">
							<input type="text" id="price" name="product[price]" value="<?php if($block->getPriceProduct($_productDetail)) echo $block->getPriceProduct($_productDetail) ?>" class="required-entry validate-zero-or-greater input-text required-entry _required" aria-required="true" />						
						</div>
					</div>
					<div class="field">
						<label class="label" ><span><?php echo __('Special Price('.$currencySymbol.'): ') ?></span></label>
						<div class="control">
							<input type="text" name="product[special_price]" value="<?php if($block->getFinalPriceProduct($_productDetail)) echo $block->getFinalPriceProduct($_productDetail) ?>" class="input-text" />						
						</div>
					</div>					
					<div class="field">
						<label class="label" ><span><?php echo __('Special Price From Date: ') ?></span></label>
						<div class="control">
							<input type="text" id="special_from_date" name="product[special_from_date]" value="<?php echo $block->formatDateTime($_productDetail->getSpecialFromDate()) ?>" class="input-text " />						
						</div>						
					</div>
					<div class="field">
						<label class="label" ><span><?php echo __('Special Price To Date: ') ?></span></label>
						<div class="control">
							<input type="text" id="special_to_date" name="product[special_to_date]" value="<?php echo $block->formatDateTime($_productDetail->getSpecialToDate()) ?>" class="input-text "  />						
						</div>						
					</div>
					<div class="field">
						<label class="label"><span><?php echo __('Quantity: ') ?></span></label>
						<div class="control">
							<input type="text" name="product[quantity_and_stock_status][qty]" value="<?php if($_quanlity) echo $_quanlity; ?>" <?php echo $block->checkShowChildHtmlDownload()?'':'disabled' ?> class="input-text validate-number " />
						</div>
					</div>
					<div class="field">
						<label class="label"><span><?php echo __('Stock Availability: ') ?></span></label>
						<div class="control">
							<?php 
								$selected=$notselected='';
								if($stockStatus){
									$selected='selected';
								}else{
									$notselected='selected';
								}
							?>
							<select name="product[quantity_and_stock_status][is_in_stock]" class="select">
								<option value="1" <?php echo $selected ?> ><?php echo __('In Stock') ?></option>
								<option value="0" <?php echo $notselected ?> ><?php echo __('Out of Stock') ?></option>
							</select>
						</div>
					</div>
					<div class="field required">
						<label class="label"><span><?php echo __('Visibility: ') ?></span></label>
						<div class="control">
							<select class="required-entry select" name="product[visibility]" aria-required="true">
								<option value=""><?php echo __('Please Select') ?></option>
								<?php foreach($visibility as $keyvi => $valuevi){ ?>
									<option value="<?php echo $keyvi?>" <?php echo $keyvi==$_productDetail->getVisibility()?'selected':'' ?> ><?php echo $valuevi ?></option>
								<?php } ?>
							</select>
						</div>
					</div>
					<?php if(count($taxcollection)){?>
					<div class="field">
						<label class="label"><span><?php echo __('Tax Class: ') ?></span></label>
						<div class="control">
							<select class="required-entry select" name="product[tax_class_id]">
								<option value="0"><?php echo __('None') ?></option>
								<?php foreach($taxcollection as $taxkey => $taxvalue){?>
								<option value="<?php echo $taxvalue['value'] ?>" <?php echo $_productDetail->getData('tax_class_id')==$taxvalue['value']?'selected':''?>><?php echo $taxvalue['label'] ?></option>
								<?php } ?>
							</select>
						</div>
					</div>
					<?php } ?>					
					<div class="field">
						<label class="label"><span><?php echo __('Weight: ') ?></span></label>
						<div class="control" data-role="weight-switcher">
							<?php if($_productDetail->getId()){ ?>
							<div class="control">
								<input type="radio" name="product[product_has_weight]" value="1" <?php echo $_hasweight?'checked':''?> />
								<label><?php echo __('Yes') ?></label>
							</div>
							<div class="control">
								<input type="radio" name="product[product_has_weight]" value="0" <?php echo !($_hasweight)?'checked':''?> />
								<label><?php echo __('No') ?></label>							
							</div>
							<?php }else{ ?>
							<div class="control">
								<input type="radio" name="product[product_has_weight]" value="1" checked="" />
								<label><?php echo __('Yes') ?></label>
							</div>
							<div class="control">
								<input type="radio" name="product[product_has_weight]" value="0" />
								<label><?php echo __('No') ?></label>							
							</div>							
							<?php } ?>						
						</div>
						<div class="control">
							<input type="text" id="weight" name="product[weight]" value="<?php echo number_format($_productDetail->getWeight(), 2) ?>" class="input-text validate-zero-or-greater" />
						</div>
					</div>
					<?php echo $block->getChildHtml('magebay_gallery') ?>
					<?php if($typeId != 'booking' && $block->checkShowChildHtmlDownload()){ ?>
						<?php echo $block->getChildHtml('marketplace_product_downloadable_item') ?>
					<?php } ?>
					<?php echo $block->getChildHtml('magebay_price_tier') ?>
					<div class="field configurable-product">
						<?php if($block->checkShowChildHtmlConfig()) { ?>
							<?php echo $block->getChildHtml('magebay_product_config_container') ?>
						<?php } ?>
						<div style="clear:both;"></div>
					</div>
					<div class="field product_cost">
						<label class="label"><span><?php echo __('Cost('.$currencySymbol.'): ') ?></span></label>
						<div class="control">
							<input type="text" class="text input-text" name="product[cost]" <?php echo $block->checkShowChildHtmlDownload()?'':'disabled' ?> value="<?php echo number_format($_productDetail->getData('cost'), 2) ?>" />
						</div>
					</div>
                    <?php if($typeId == 'booking') : ?>
                        <?php echo $this->getLayout()->createBlock('Magebay\Bookingsystem\Block\Marketplace\MkBooking')->setBKProduct($_productDetail)->setTemplate('Magebay_Bookingsystem::marketplace/mk_edit.phtml')->toHtml();  ?>
                    <?php else : ?>
                        <?php echo $block->getChildHtml('magebay_custom_options') ?>
                    <?php endif; ?>
				</div>
				<div class="field block-button">
					<button type="submit" class="button" title="<?php echo __('Save') ?>" >
						<span><span><?php echo __('Save') ?></span></span>
					</button>
				</div>
			</fieldset>
		</form>
		<script>
    	    require([
    	        "jquery",
    			'Magento_Ui/js/modal/alert',
    	        "mage/mage",			
    	        'mage/calendar'
    	    ], function($,alert){
    	        var dataForm = $('#form-seller-add-newproduct');
    	        dataForm.mage('validation', {});
    			
    	        $("#special_from_date").calendar({'dateFormat':'mm/dd/yy'});			
    			$("#special_to_date" ).calendar({'dateFormat':'mm/dd/yy'});			
    	        var i=2;
    			
    			$('.input-text').change(function(){
    				var vl1 = $(this).val();
    				var regex = /(<([^>]+)>)/ig;
    				var vl2 = vl1 .replace(regex, "");
    				$(this).val(vl2);	
    		    });
    			$('input#sku').change(function(){
                    $('.sku_false,.sku_true').hide();
    				var vallen=$('input#sku').val();				
    				if(vallen==0){					
    					alert({
    						title: '<?php echo __('Sku Product') ?>',
    						content: "<?php echo __('Sku not empty') ?>",
    						actions: {
    							always: function(){}
    						}
    					});							
    				}else{
    					$.ajax({
    						url: "<?php echo $block->getUrl('marketplace/product/validateSku') ?>",
    						type: "POST",
    						data: {sku:$('input#sku').val()},
    						dataType: 'text',
    						beforeSend:function(){
                                $('#mb-ajaxloading').show();
    						},
    						error:function(){},
    						success:function($data){
                                $('#mb-ajaxloading').hide();
    							data=$.parseJSON($data);
    							if(!data.status){
    								$('.sku_true').show();
    							}else{								
    								$('.sku_false').show();							
    								$("input#sku").val('');
    							}
    						}
    					});
    				}
    			});			
    			$('.categorycollection').delegate('.mst-push,.mst-pull','click',function(){	
    				if($(this).hasClass('mst-push')){
    					$(this).removeClass('mst-push').addClass('mst-pull');
    					var self=this;
    					var _htmlbefore_load='<span class="mst-beforeload"></span>';
    					if($(this).siblings('.category-block').length){
    						$(this).siblings('.category-block').slideToggle();
    					}else{
    						$.ajax({
    							url:'<?php echo $block->getUrl('marketplace/product/ajaxCategory') ?>',
    							type:'POST',
    							data:{categoryid:$(this).siblings('input[type=checkbox].mst-checkbox').val(),level:parseInt($(this).data('level')),id:<?php echo $_productDetail->getId()?$_productDetail->getId():0 ?>},
    							dataType:'text',
    							beforeSend:function(){
    								$(self).prepend(_htmlbefore_load);
    							},
    							error:function(xhr, textStatus, error){
    								
    							},
    							success:function(data){
    								$('span.mst-beforeload').remove();
    								 var html=$.parseJSON(data);
    								 $(self).parent().append(html.content);
    							}
    						});					
    					}
    				}else if($(this).hasClass('mst-pull')){
    					$(this).removeClass('mst-pull').addClass('mst-push');
    					$(this).siblings('.category-block').slideToggle();
    				}
    			});
                $( ".actions-buttons .dropdown-toggle" ).click(function() {
                    $( ".actions-buttons .dropdown-menu" ).toggle();
        		});
                $('.save_product').click(function(event){
                    $('.type_save').val($(this).attr('redirect'));
                    dataForm.submit();
                    event.preventDefault();
                });
    		});		
		</script>
		<script>
			require([
				"jquery",
				"Magebay_Marketplace/catalog/type-events"
			], function($, TypeSwitcher){
				var $form = $('[data-form=edit-product]');
				$form.data('typeSwitcher', TypeSwitcher.init());
			});
		</script>
		<script type="text/x-magento-init">
			{
				"*": {
					"Magebay_Marketplace/js/product/weight-handler": {},
					"Magebay_Marketplace/catalog/apply-to-type-switcher": {}
				}
			}
		</script>		
	</div>
</div>
<style>
    .btn-add-products{
        padding: 7px 33px;
    }
    .page-head-actions {
        background: #f8f8f8 none repeat scroll 0 0;
        border: 1px solid #e3e3e3;
        padding: 10px 15px;
    }
    .page-head-actions .actions-buttons {
        text-align: right;
    }
    .btn-group.prod-button {
        display: inline-block !important;
    }
    .btn-group, .btn-group-vertical {
        display: inline-block;
        position: relative;
        vertical-align: middle;
    }
    .btn-group > .btn + .dropdown-toggle {
        padding-left: 8px;
        padding-right: 8px;
    }
    .btn-group .btn + .btn, .btn-group .btn + .btn-group, .btn-group .btn-group + .btn, .btn-group .btn-group + .btn-group {
        margin-left: -1px;
    }
    .btn-group > .btn-group:last-child:not(:first-child) > .btn:first-child, .btn-group > .btn:last-child:not(:first-child), .btn-group > .dropdown-toggle:not(:first-child) {
        border-bottom-left-radius: 0;
        border-top-left-radius: 0;
    }
    .btn-group-vertical > .btn, .btn-group > .btn {
        float: left;
        position: relative;
    }
    .btn.btn-red {
        background-color: #eb5202;
        border-color: #b25524;
        color: #fff;
    }
    button:not(.primary) {
        box-shadow: 0 1px 0 0 #fff inset, 0 -1px 0 0 rgba(204, 204, 204, 0.3) inset;
    }
    .btn .caret, .btn-group > .btn:first-child {
        margin-left: 0;
    }
    .caret {
        border-left: 4px solid transparent;
        border-right: 4px solid transparent;
        border-top: 4px dashed;
        display: inline-block;
        height: 0;
        margin-left: 2px;
        vertical-align: middle;
        width: 0;
    }
    .btn-group.prod-button .dropdown-menu::before, .btn-group.prod-button .dropdown-menu::after {
        border: medium none !important;
    }
    .btn-group > .dropdown-menu::before, .dropdown-toggle > .dropdown-menu::before, .dropdown > .dropdown-menu::before {
        border-bottom: 8px solid #e0e0e0;
        border-left: 8px solid transparent;
        border-right: 8px solid transparent;
        content: "";
        display: inline-block !important;
        left: 9px;
        position: absolute;
        right: auto;
        top: -8px;
    }
    *, *::after, *::before {
        box-sizing: border-box;
    }
    .btn-group.prod-button .dropdown-menu::before, .btn-group.prod-button .dropdown-menu::after {
        border: medium none !important;
    }
    .btn-group > .dropdown-menu::after, .dropdown-toggle > .dropdown-menu::after, .dropdown > .dropdown-menu::after {
        border-bottom: 7px solid #fff;
        border-left: 7px solid transparent;
        border-right: 7px solid transparent;
        content: "";
        display: inline-block !important;
        left: 10px;
        position: absolute;
        right: auto;
        top: -7px;
    }
    .btn-group.prod-button .dropdown-menu {
        box-shadow: 2px 2px rgba(102, 102, 102, 0.1);
        margin: 2px 0 0;
        min-width: 140px;
    }
    .btn-group > .dropdown-menu, .dropdown-toggle > .dropdown-menu, .dropdown > .dropdown-menu {
        margin-top: 10px;
    }
    .dropdown-menu {
        background-clip: padding-box;
        background-color: #fff;
        border: 1px solid rgba(0, 0, 0, 0.15);
        border-radius: 4px;
        box-shadow: 0 6px 12px rgba(0, 0, 0, 0.176);
        display: none;
        font-size: 14px;
        left: 0;
        list-style: outside none none;
        margin: 2px 0 0;
        min-width: 160px;
        padding: 5px 0;
        position: absolute;
        text-align: left;
        top: 100%;
        z-index: 1000;
        width: 146px;
    }
    .btn-group > .btn-group, .btn-toolbar .btn, .btn-toolbar .btn-group, .btn-toolbar .input-group, .col-xs-1, .col-xs-10, .col-xs-11, .col-xs-12, .col-xs-2, .col-xs-3, .col-xs-4, .col-xs-5, .col-xs-6, .col-xs-7, .col-xs-8, .col-xs-9, .dropdown-menu {
        float: left;
    }
    a, button, code, div, img, input, label, li, p, pre, select, span, svg, table, td, textarea, th, ul {
        border-radius: 0 !important;
    }
    .dropdown-menu > li > a {
        clear: both;
        color: #6f6f6f;
        display: block;
        font-weight: 300;
        line-height: 18px;
        padding: 8px 16px;
        text-decoration: none;
        white-space: nowrap;
    }
    .dropdown-menu > li > a:focus, .dropdown-menu > li > a:hover {
        color: #262626;
        background-color: #e3e3e3;
    }
</style>