<?php

/**
 * @var $viewModel \Daytours\Checkout\ViewModel\ProductListToOperations
 * @var $orderByIncrementId \Magento\Sales\Model\Order
 */

$viewModel = $block->getViewModel();
$orderByIncrementId = $viewModel->getOrderById($this->getOrderId());


?>
<div asd="<?= $this->getOrderId() ?>" add="<?= json_encode($orderByIncrementId->getData()) ?>"></div>
<?php if($orderByIncrementId):

    $listProduct = $orderByIncrementId->getAllItems();
    ?>



    <table asd="<?= $this->getOrderId() ?>" add="<?= json_encode($orderByIncrementId->getData()) ?>">
        <?php
        foreach ($listProduct as $item):
            $product = $item->getProduct();
            ?>
            <tr>
                <td><strong>Nombre:</strong></td>
                <td><?= $product->getName(); ?></td>
            </tr>
            <tr>
                <td><strong>SKU:</strong></td>
                <td><?= $product->getSku(); ?></td>
            </tr>
            <?php
            $itemOptions = $item->getProductOptions();
            $productOptions = $viewModel->getAllOptions($itemOptions);
            if( $productOptions ){
                ?>
                <tr>
                    <td colspan="2"><strong>Opciones:</strong></td>
                </tr>
                <tr>
                    <td></td>
                    <td>
                        <table>
                            <?php foreach ($productOptions as $option): ?>
                                <?php if( $option['label'] == 'regular_services' ): ?>
                                    <?php $regularService = json_decode($option['value']); ?>
                                    <?php if( count($regularService) > 0 ): ?>
                                        <?php foreach ($regularService as $itemR): ?>
                                            <tr>
                                                <td><strong><?= $itemR->label ?>:</strong></td>
                                                <td><?= $itemR->price ?> x <?= $itemR->qty ?></td>
                                            </tr>
                                        <?php endforeach; ?>
                                    <?php endif; ?>
                                <?php else: ?>
                                    <tr>
                                        <td><strong><?= $option['label'] ?>:</strong></td>
                                        <td><?= $option['value'] ?></td>
                                    </tr>
                                <?php endif; ?>
                            <?php endforeach; ?>
                        </table>
                    </td>
                </tr>
                <tr>
                    <td colspan="2">---------------------------------------</td>
                </tr>
                <?php
            }
        endforeach;
        ?>
    </table>
<?php endif; ?>
